suitenumerique/docs

Makefile, docker-compose.yml, src/frontend/Dockerfile, src/frontend/apps/e2e/__tests__/app-impress/pad-editor.spec.ts, src/frontend/apps/impress/.env.development, src/frontend/apps/impress/.env.production, src/frontend/apps/impress/src/custom-next.d.ts, src/frontend/apps/impress/src/features/pads/pad/components/BlockNoteEditor.tsx, src/frontend/apps/impress/src/features/pads/pad/components/PadEditor.tsx, src/frontend/apps/impress/src/features/pads/pad/store/index.ts, src/frontend/apps/impress/src/features/pads/pad/store/usePadStore.tsx, src/frontend/apps/impress/src/features/pads/pad/utils.ts, src/frontend/apps/impress/src/features/pads/pads-panel/components/PadList.tsx, src/frontend/apps/impress/src/features/pads/pads-panel/components/PanelActions.tsx, src/frontend/apps/impress/src/features/pads/pads-panel/store/index.ts, src/frontend/apps/impress/src/features/pads/pads-panel/store/usePadPanelStore.tsx, src/frontend/apps/y-webrtc-signaling/.eslintrc.cjs, src/frontend/apps/y-webrtc-signaling/nodemon.json, src/frontend/apps/y-webrtc-signaling/package.json, src/frontend/apps/y-webrtc-signaling/src/server.ts, src/frontend/apps/y-webrtc-signaling/tsconfig.json, src/frontend/yarn.lock
Create y-webrtc server.
It will make the pads collaboratives.
Show collaboration between Firefox and Chrome:
[scrnli_4_8_2024_12-07-43 PM.webm](https://github.com/numerique-gouv/impress/assets/25994652/58d750eb-01ab-488f-836d-3e855e86292a)
=> ✨(frontend) y-webrtc-signaling

src/frontend/apps/e2e/__tests__/app-impress/pad-editor.spec.ts, src/frontend/apps/impress/src/features/pads/pad-tools/components/PDFButton.tsx, src/frontend/apps/impress/src/features/pads/pad-tools/components/PadToolBox.tsx, src/frontend/apps/impress/src/features/pads/pad-tools/components/PrintToPDFButton.tsx, src/frontend/apps/impress/src/features/templates/template/components/TemplateEditor.tsx
Give the possibility to choose between different template thanks to a select box.
[scrnli_4_17_2024_5-44-17 PM.webm](https://github.com/numerique-gouv/impress/assets/25994652/1493ff9f-9a64-4990-a20e-2fca8ea61a39)
=> ✨select template

src/helm/env.d/staging/secrets.enc.yaml, src/helm/env.d/staging/values.impress.yaml.gotmpl, src/helm/extra/templates/secrets.yaml, src/helm/helmfile.yaml
Avoid secrets to be visible from running deployments
=> 💚(ci) improve secrets for k8s deployment

src/backend/core/admin.py, src/frontend/apps/impress/src/components/Box.tsx, src/frontend/apps/impress/src/core/auth/Auth.tsx, src/frontend/apps/impress/src/layouts/PageLayout.tsx, src/frontend/apps/impress/src/pages/coming-soon/index.tsx, src/helm/env.d/production/secrets.enc.yaml, src/helm/env.d/production/values.impress.yaml.gotmpl, src/helm/extra/templates/secrets.yaml, src/helm/helmfile.yaml
Deploy to production 🚀🚀
Make everything ready for production, we will add a "Coming soon" page until we decide the features available are enough
for sharing the website.
=> 🚀Production

CHANGELOG.md, src/helm/env.d/production/values.impress.yaml.gotmpl, src/mail/package.json, src/tsclient/package.json
- Coming Soon page
- Impress, project to manage your documents easily and collaboratively
=> 🔖(minor) initial release to 0.1.0

src/helm/env.d/staging/secrets.enc.yaml, src/helm/env.d/staging/values.impress.yaml.gotmpl
To fit with the production environment, we need to add the djangoSuperUserEmail secret to the staging environment.
=> 🔐(helm) add djangoSuperUserEmail secret

scripts/install-hooks.sh, scripts/updatekeys.sh
Add git hook to avoid secret leaks
=> 💚(CI) Add git hook

CHANGELOG.md, src/frontend/apps/e2e/__tests__/app-impress/pad-editor.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-tools.spec.ts, src/frontend/apps/impress/src/features/pads/pad-editor/components/BlockNoteEditor.tsx, src/frontend/apps/impress/src/features/pads/pad-editor/components/PadEditor.tsx, src/frontend/apps/impress/src/features/pads/pad-editor/hook/useSavePad.tsx, src/frontend/apps/impress/src/features/pads/pad-tools/components/PadToolBox.tsx, src/frontend/packages/eslint-config-impress/playwright.js
PR to manage the right on the pad.
=> 🛂(frontend) right pad editor

src/frontend/apps/impress/src/pages/accessibility/index.tsx, src/frontend/apps/impress/src/pages/legal-notice/index.tsx, src/frontend/apps/impress/src/pages/personal-data-cookies/index.tsx, src/frontend/packages/i18n/i18next-parser.config.mjs
Makes the legal pages translatable.
=> 🌐(frontend) legal pages translatable

CHANGELOG.md, src/frontend/apps/e2e/.gitignore, src/frontend/apps/e2e/__tests__/app-impress/404.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/auth.setup.ts, src/frontend/apps/e2e/__tests__/app-impress/common.ts, src/frontend/apps/e2e/__tests__/app-impress/footer.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/header.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/language.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-add-members.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-create.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-editor.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-member-delete.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-member-grid.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-panel.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-tools.spec.ts, src/frontend/apps/e2e/playwright.config.ts
We will cache the login token in the browser storage and reuse it between tests.
This will speed up the tests and reduce the load on the server making everything more stable.
=> ⚡️(e2e) unique login between tests

.github/workflows/docker-hub.yml
=> 🐛(CI) fix ci issue

.github/workflows/deploy.yml, .github/workflows/docker-hub.yml, .github/workflows/impress.yml, .gitmodules, src/helm/env.d/preprod/secrets.enc.yaml, src/helm/env.d/production/secrets.enc.yaml, src/helm/env.d/staging/secrets.enc.yaml, src/helm/helmfile.yaml
- remove deplucate declaration
- simplify helmfile
- use symlink
=> 🐛(CI) improve submodule

src/frontend/apps/impress/src/features/pads/pad-editor/stores/usePadStore.tsx, src/frontend/apps/y-webrtc-signaling/src/server.ts
🐛(frontend) fix bug multi ws connection
In collaborative mode, only the first document
connected was being shared. This was due to the
fact that the webrtc server was managing only
one connection at a time. This commit fixes this
bug by managing multiple connections.
=> 🐛webrtc multi channel

CHANGELOG.md, src/frontend/apps/impress/src/components/TextErrors.tsx, src/frontend/apps/impress/src/features/pads/members/members-grid/__tests__/ModalRole.test.tsx, src/frontend/apps/impress/src/features/pads/members/members-grid/components/MemberAction.tsx, src/frontend/apps/impress/src/features/pads/members/members-grid/components/ModalDelete.tsx, src/frontend/apps/impress/src/features/pads/members/members-grid/components/ModalRole.tsx, src/frontend/apps/impress/src/features/pads/pad-management/components/ModalRemovePad.tsx, src/frontend/apps/impress/src/features/pads/pad-management/components/ModalUpdatePad.tsx, src/frontend/apps/impress/src/features/pads/pad-tools/components/ModalPDF.tsx, src/frontend/apps/impress/src/features/pads/pads-panel/__tests__/PanelPads.test.tsx, src/frontend/apps/impress/src/features/pads/pads-panel/components/PadList.tsx, src/frontend/apps/impress/src/pages/docs/[id].tsx
Improve the ui error and message info ui by using the Cunningham Alert component.
=> ♻️(frontend) improve the error and message info ui

CHANGELOG.md, src/frontend/apps/e2e/__tests__/app-impress/common.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-add-members.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-create.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/pad-member-delete.spec.ts, src/frontend/apps/impress/.eslintrc.js, src/frontend/apps/impress/.gitignore, src/frontend/apps/impress/.prettierignore, src/frontend/apps/impress/next.config.js, src/frontend/apps/impress/package.json, src/frontend/apps/impress/public/assets/img-not-found.svg, src/frontend/apps/impress/src/core/service-worker.ts, src/frontend/apps/impress/src/features/pads/members/members-add/components/ModalAddMembers.tsx, src/frontend/apps/impress/src/pages/_app.tsx, src/frontend/apps/impress/src/pages/offline/index.tsx, src/frontend/package.json, src/frontend/yarn.lock
Offline mode 🚀🚀
We save part of the website in cache, visited document are saved in cache. 
We will use the [CacheFirst Strategie](https://developer.chrome.com/docs/workbox/modules/workbox-strategies#cache_first_cache_falling_back_to_network), making the website blazing fast in production mode.
=> ✨Offline mode

src/frontend/apps/impress/src/features/docs/doc-tools/components/DocToolBox.tsx, src/frontend/apps/impress/src/features/docs/doc-tools/components/ModalPDF.tsx, src/frontend/apps/impress/src/features/service-worker/conf.ts, src/frontend/apps/impress/src/features/service-worker/service-worker-api.ts, src/frontend/apps/impress/src/features/service-worker/service-worker.ts
Same part were served by the cache first, causing unwanted behavior.
=> 🐛(service-worker) networkFirst on api request

src/frontend/apps/impress/src/features/service-worker/ApiPlugin.ts, src/frontend/apps/impress/src/features/service-worker/__tests__/ApiPlugin.test.tsx
When we updated the doc successfully then directly pass offline, the cache was not updated.
It is because a successful update didn't update the cache of the doc-item.
=> 🗃️(service-worker) cache successfull update in doc-item

docker-compose.yml, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/yarn.lock, src/mail/yarn.lock
Lot of dependencies were outdated, so we updated them.
=> ⬆️(mail) bump mail dependencies

src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx, src/frontend/apps/impress/src/features/docs/members/members-list/components/MemberItem.tsx
=> ♻️ Fine tuning

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/apps/y-webrtc-signaling/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/helm/env.d/preprod/values.impress.yaml.gotmpl, src/helm/env.d/production/values.impress.yaml.gotmpl, src/mail/package.json, src/tsclient/package.json
- 🤡(demo) generate dummy documents on dev users #120 
- ✨(frontend) create side modal component #134
- ✨(frontend) Doc grid actions (update / delete) #136
- ✨(frontend) Doc editor header information #137
- ♻️(frontend) replace docs panel with docs grid #120
- ♻️(frontend) create a doc from a modal #132
- ♻️(frontend) manage members from the share modal #140
----
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.0.0...v1.1.0
=> 🔖(minor) minor release to 1.1.0

.sops.yaml, src/helm/env.d/dev/secrets.enc.yaml
=> 🔐(secret) add spaccoud age key

src/backend/core/models.py, src/backend/core/tests/test_models_templates.py
To leverage the automatic deletion of temporary files, we do the conversion inside the with context.
Even if the conversion fails, the temporary file will be deleted.
=> ♻️(backend) automatic delete temporary files

CHANGELOG.md, docs/release.md, src/helm/env.d/preprod/values.impress.yaml.gotmpl, src/helm/env.d/production/values.impress.yaml.gotmpl, src/helm/impress/templates/secret.yaml
We are stoping to secure the site with htaccess, so we can remove it from the project.
=> 🔥(helm) remove htaccess

CHANGELOG.md, Makefile, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/apps/y-webrtc-signaling/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/helm/env.d/preprod/values.impress.yaml.gotmpl, src/helm/env.d/production/values.impress.yaml.gotmpl, src/mail/package.json
- ♻️ Change ordering docs datagrid #195
- 🔥(helm) use scaleway email #194
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.2.0...v1.2.1
=> 🔖(patch) release 1.2.1

CHANGELOG.md, src/frontend/apps/e2e/__tests__/app-impress/doc-summary.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/doc-version.spec.ts, src/frontend/apps/impress/src/components/BoxButton.tsx, src/frontend/apps/impress/src/components/Panel.tsx, src/frontend/apps/impress/src/features/docs/doc-editor/components/DocEditor.tsx, src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx, src/frontend/apps/impress/src/features/docs/doc-summary/components/Summary.tsx, src/frontend/apps/impress/src/features/docs/doc-summary/components/index.ts, src/frontend/apps/impress/src/features/docs/doc-summary/index.ts, src/frontend/apps/impress/src/features/docs/doc-summary/stores/index.ts, src/frontend/apps/impress/src/features/docs/doc-summary/stores/useDocSummaryStore.tsx, src/frontend/apps/impress/src/features/docs/doc-versioning/components/index.ts, src/frontend/apps/impress/src/features/docs/doc-versioning/stores/useDocVersionStore.tsx
We created a summary panel, that will list the headers of our document and link to them.
[scrnli_9_3_2024_3-45-08 PM.webm](https://github.com/user-attachments/assets/32c11786-10c4-4ef2-8dad-39f8863d929f)
=> ✨ Summary frontend

src/helm/env.d/production/values.impress.yaml.gotmpl
The set the correct media storage name for production environment.
=> 🔧(helm) change production media storage name

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/env.d/preprod/values.impress.yaml.gotmpl, src/helm/env.d/production/values.impress.yaml.gotmpl, src/mail/package.json
- ✨Add image attachments with access control
- ✨(frontend) Upload image to a document #211
- ✨(frontend) Summary #223
- ✨(frontend) update meta title for docs page #231
- 💄(frontend) code background darkened on editor #214
- 🔥(frontend) hide markdown button if not text #213
- 🐛 Fix emoticon in pdf export #225
- 🐛 Fix collaboration on document #226
- 🐛 (docker) Fix compatibility with mac #230
- 🔥(frontend) remove saving modal #213
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.2.1...v1.3.0
=> 🔖(minor) release 1.3.0

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/env.d/preprod/values.impress.yaml.gotmpl, src/helm/env.d/production/values.impress.yaml.gotmpl, src/mail/package.json
- ✨(backend) Add link public/authenticated/restricted access with read/editor roles #234
- ✨(frontend) add copy link button #235
- 🛂(frontend) access public docs without being logged #235
- ♻️(backend) Allow null titles on documents for easier creation #234
- 🛂(backend) stop to list public doc to everyone #234
- 🚚(frontend) change visibility in share modal #235 
- ⚡️(frontend) Improve summary #244
- 🐛(backend) Fix forcing ID when creating a document via API endpoint #234
- 🐛 Rebuild frontend dev container from makefile #248
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.3.0...v1.4.0
=> 🔖(minor) release 1.4.0

.github/workflows/helmfile-linter.yaml, src/helm/impress/templates/backend_job.yaml, src/helm/impress/templates/backend_job_createsuperuser.yaml
Add a github job to run helmfile linter on PR
Add argocd annotation to fix job syncing issue
=> ✨(ci) add helmfile linter and fix issue in argocd sync

README.md
Minimal update to the readme file to better reflect the project.
=> 📝(project) update README.md

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/env.d/preprod/values.impress.yaml.gotmpl, src/helm/env.d/production/values.impress.yaml.gotmpl, src/mail/package.json
- 🐛(db) fix users duplicate #316
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.5.0...v1.5.1
=> 🔖(patch) release 1.5.1

src/frontend/apps/impress/src/features/docs/doc-editor/components/AIButton.tsx, src/frontend/apps/impress/src/i18n/translations.json
Before release, we do a last check on the preproduction environment.
This PR fixes or improves small things that we noticed during our checkup.
=> ♻️Small improvement before release to 1.6.0

CHANGELOG.md, src/frontend/package.json, src/frontend/yarn.lock
Version 0.17.0 of Blocknote fixes the copy paste issue in the editor with Firefox.
=> ⬆️(frontend) upgrade blocknote to 0.17.0

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/env.d/preprod/values.impress.yaml.gotmpl, src/helm/env.d/production/values.impress.yaml.gotmpl, src/mail/package.json
- ✨AI to doc editor #250
- ✨(backend) allow uploading more types of attachments #309
- ✨(frontend) add buttons to copy document to clipboard as HTML/Markdown #300
- ♻️(frontend) More multi theme friendly #325
- ♻️ Bootstrap frontend #257
- ♻️ Add username in email #314
- 🛂(backend) do not duplicate user when disabled
- 🐛(frontend) invalidate queries after removing user #336
- 🐛(backend) Fix dysfunctional permissions on document create #329
- 🐛(backend) fix nginx docker container #340
- 🐛(frontend) fix copy paste firefox #353
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.5.1...v1.6.0
=> 🔖(minor) release 1.6.0

CONTRIBUTING.md, Makefile
We add a new section in the CONTRIBUTING.md file to explain how to update the CHANGELOG.md file. 
We improve the pull request section as well.
=> 📝(contributing) add changelog part in contributing

CONTRIBUTING.md
Added a link to the github project so that contributors know what to prioritize.
=> 📝(Documentation) add an issue selection section

CHANGELOG.md, src/frontend/apps/impress/src/components/Box.tsx, src/frontend/apps/impress/src/components/BoxButton.tsx, src/frontend/apps/impress/src/components/Card.tsx, src/frontend/apps/impress/src/features/docs/doc-header/components/DocHeader.tsx, src/frontend/apps/impress/src/features/footer/Footer.tsx
In order to facilitate DX and not to use a string in the code for the css. We add the $styledCss props to the Box component. This object comes from Styled component
=> ✨(frontend) add styledCss props to Box component

CHANGELOG.md, src/frontend/apps/e2e/__tests__/app-impress/doc-grid.spec.ts, src/frontend/apps/impress/src/components/BoxButton.tsx, src/frontend/apps/impress/src/components/DropButton.tsx, src/frontend/apps/impress/src/components/DropdownMenu.tsx, src/frontend/apps/impress/src/components/index.ts, src/frontend/apps/impress/src/features/docs/doc-management/components/ModalRemoveDoc.tsx, src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGrid.tsx, src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridActions.tsx, src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridLoader.tsx
=> 💄(frontend) add docgrid options button

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/extra/Chart.yaml, src/helm/helmfile.yaml, src/helm/impress/Chart.yaml, src/mail/package.json
🐛(frontend) link not clickable and flickering firefox #457
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.8.0...v1.8.1
=> 🔖(patch) release 1.8.1

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/extra/Chart.yaml, src/helm/helmfile.yaml, src/helm/impress/Chart.yaml, src/mail/package.json
- ♻️(SW) change strategy html caching #460
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.8.1...v1.8.2
=> 🔖(patch) release 1.8.2

src/backend/core/services/ai_services.py, src/frontend/apps/e2e/__tests__/app-impress/config.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts, src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
Fix problems found when checking the preproduction before doing a release.
=> 🎨Fine tuning v1.9.0

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/extra/Chart.yaml, src/helm/helmfile.yaml, src/helm/impress/Chart.yaml, src/mail/package.json
- ✨(backend) annotate number of accesses on documents in list view #429
- ✨(backend) allow users to mark/unmark documents as favorite #429
- 🔒️(collaboration) increase collaboration access security #472
- 🔨(frontend) encapsulated title to its own component #474
- ⚡️(backend) optimize number of queries on document list view #429
- ♻️(frontend) stop to use provider with version #480
- 🚚(collaboration) change the websocket key name #480
- 🐛(frontend) fix initial content with collaboration #484
- 🐛(frontend) Fix hidden menu on Firefox #468
- 🐛(backend) fix sanitize problem IA #490
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.8.2...v1.9.0
=> 🔖(minor) release 1.9.0

src/backend/core/api/serializers.py, src/backend/core/services/collaboration_services.py, src/backend/core/services/converter_services.py, src/backend/core/tests/documents/test_api_documents_create_for_owner.py, src/backend/core/tests/test_services_converter_services.py, src/backend/impress/settings.py, src/frontend/servers/y-provider/__tests__/server.test.ts, src/frontend/servers/y-provider/src/env.ts, src/frontend/servers/y-provider/src/middlewares.ts, src/helm/env.d/dev/values.impress.yaml.gotmpl
=> Fix server-to-server doc creation

.github/workflows/docker-hub.yml, CHANGELOG.md, bin/Tiltfile, docker-compose.yml, src/frontend/Dockerfile, src/frontend/servers/y-provider/Dockerfile
Improve y-provider image by having the `node_modules` as small as possible.
=> ⚡️(docker) improve y-provider image

.github/workflows/impress-frontend.yml, CHANGELOG.md, src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts, src/frontend/apps/e2e/playwright.config.ts, src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteToolbar.tsx, src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
e2e test start to be very flaky, we fix a bug that create flakiness, plus improve playwright installation.
-  🐛(frontend) fix rerendering when doc is saving
- ⚡️(ci) playwright install
- ⚡️(e2e) set maxFailures with CI
=> ⚡️e2e flakiness

CHANGELOG.md, src/frontend/apps/e2e/__tests__/app-impress/doc-create.spec.ts, src/frontend/apps/impress/src/features/docs/doc-header/components/DocTitle.tsx, src/frontend/apps/impress/src/features/docs/doc-share/component/DocShareModal.tsx
- Fixed minor bugs in the frontend codebase for improved stability.
- Enhanced DocTitle component to update title display dynamically using useEffect.
- Refactored DocShareModal to improve modal content height calculation for better responsiveness.
=> 💄(frontend) fix minor bugs and enhance DocTitle and DocShareModal

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/helmfile.yaml, src/mail/package.json
- 🔧(backend) add option to configure list of essential OIDC claims #525 & #531
- 🔧(helm) add option to disable default tls setting by @dominikkaminski #519
- 💄(frontend) Add left panel #420
- 💄(frontend) add filtering to left panel #475
- ✨(frontend) new share modal ui #489
- ✨(frontend) add favorite feature #515
- 🏗️(yjs-server) organize yjs server #528
- ♻️(frontend) better separation collaboration process #528
- 💄(frontend) updating the header and leftpanel for responsive #421
- 💄(frontend) update DocsGrid component #431
- 💄(frontend) update DocsGridOptions component #432
- 💄(frontend) update DocHeader ui #448
- 💄(frontend) update doc versioning ui #463
- 💄(frontend) update doc summary ui #473
- 🐛(backend) fix create document via s2s if sub unknown but email found #543
- 🐛(frontend) …
=> 🔖(major) release 2.0.0

CHANGELOG.md, src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridItem.tsx
An alignment problem has occurred. An omission of condition if it is mobile or desktop
=> 💄(frontend) improve DocsGridItem responsive padding

README.md
Found a few errors after proof-reading the (excellent!!) README
=> ✏️(readme) fix a few typos

CHANGELOG.md, README.md
See https://github.com/suitenumerique/docs/issues/622
=> 📝(doc) minor README.md formatting and wording enhancements

CHANGELOG.md, src/frontend/apps/e2e/__tests__/app-impress/home.spec.ts, src/frontend/apps/impress/src/features/home/components/HomeBottom.tsx, src/frontend/apps/impress/src/features/home/components/HomeContent.tsx, src/frontend/apps/impress/src/features/home/components/HomeSection.tsx
We decided to add the open source section on the homepage of Docs.
[scrnli_C6p141AtVz5McD.webm](https://github.com/user-attachments/assets/08fae1e5-d4c9-4c02-9819-2dece58cae69)
=> ✨(frontend) add open source section homepage

src/backend/core/models.py, src/backend/core/tests/test_models_documents.py
To determine the descendant to restore or not, we were looking building a complex exclude clause. This can be simplify focusing only on data we already have without making an extra query to fetch the list of descendant to exclude.
=> ⚡️(back) restrict documents to restore using only the queryset

CHANGELOG.md, src/frontend/apps/e2e/__tests__/app-impress/doc-export.spec.ts, src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx, src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteSuggestionMenu.tsx, src/frontend/apps/impress/src/features/docs/doc-editor/components/custom-blocks/DividerBlock.tsx, src/frontend/apps/impress/src/features/docs/doc-editor/components/custom-blocks/QuoteBlock.tsx, src/frontend/apps/impress/src/features/docs/doc-editor/components/custom-blocks/index.ts, src/frontend/apps/impress/src/features/docs/doc-editor/styles.tsx, src/frontend/apps/impress/src/features/docs/doc-export/blocks-mapping/dividerDocx.tsx, src/frontend/apps/impress/src/features/docs/doc-export/blocks-mapping/dividerPDF.tsx, src/frontend/apps/impress/src/features/docs/doc-export/blocks-mapping/index.ts, src/frontend/apps/impress/src/features/docs/doc-export/mappingDocx.tsx, src/frontend/apps/impress/src/features/docs/doc-export/mappingPDF.tsx
Add a divider in the editor.
[scrnli_pCdmkyoMeEQS2d.webm](https://github.com/user-attachments/assets/306d9030-f3b6-48c2-bfde-6ffa7b921bfe)
=> ✨Add divider

src/frontend/apps/e2e/__tests__/app-impress/common.ts, src/frontend/apps/e2e/__tests__/app-impress/doc-grid.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/doc-member-list.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/doc-visibility.spec.ts
=> 🐛(frontend) fix flakiness e2e tests title doc

.github/workflows/docker-hub.yml, CHANGELOG.md
The notify-argocd workflow was not working correctly. The html_url sent to argocd was not the good one anymore.
=> 🐛(action) fix notify-argocd workflow

src/frontend/apps/impress/src/features/home/components/HomeContent.tsx
Fixing a typo on the landing page.
It shouldn't be past tense. If figured this is small enough not to warrant a changelog entry.
=> 📝(docs) fix typo

src/frontend/apps/impress/src/features/header/components/Title.tsx, src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
=> 🩹 Small frontend improvement

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/apps/impress/src/features/left-panel/components/LeftPanelHeader.tsx, src/frontend/apps/impress/src/hook/useCmdK.tsx, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/helmfile.yaml, src/helm/impress/Chart.yaml, src/mail/package.json
- 📝(doc) add publiccode.yml #770
- 🚸(frontend) ctrl+k modal not when editor is focused #712
- 🐛(back) allow only images to be used with the cors-proxy #781
- 🐛(backend) stop returning inactive users on the list endpoint #636
- 🔒️(backend) require at least 5 characters to search for users #636
- 🔒️(back) throttle user list endpoint #636
- 🔒️(back) remove pagination and limit to 5 for user list endpoint #636
=> 🔖(minor) release 2.6.0

README.md
We need to double-check our legal constraints regarding the use of XL packages within Docs. In the meantime, sends a message to potential reusers.
cc @lunika @virgile-dev @YousefED
=> 📄(legal) add warning about legal compliance

docs/env.md, docs/installation.md
Describe all options for the docs backend container. 
Add a table with options in the installation.md
=> 📝(docs) describe environmental options for docs backend

CHANGELOG.md, docs/env.md, env.d/development/common.dist, src/backend/core/api/viewsets.py, src/backend/core/tests/test_api_config.py, src/backend/impress/settings.py, src/frontend/apps/e2e/__tests__/app-impress/common.ts, src/frontend/apps/e2e/__tests__/app-impress/config.spec.ts, src/frontend/apps/e2e/__tests__/app-impress/home.spec.ts, src/frontend/apps/impress/src/core/config/api/useConfig.tsx, src/frontend/apps/impress/src/features/auth/components/Auth.tsx, src/frontend/apps/impress/src/pages/home/index.tsx, src/helm/env.d/dev/values.impress.yaml.gotmpl
We give the possibility to display or not the homepage thanks to a feature flag.
If the homepage feature flag is not activated, the user will be directly redirected to the IDP.
New settings to have the homepage displayed or not
```sh
FRONTEND_HOMEPAGE_FEATURE_ENABLED=[boolean]  
```
=> 🚩Homepage feature flag

CHANGELOG.md, src/backend/impress/settings.py
C.f. https://mozilla-django-oidc.readthedocs.io/en/latest/settings.html#OIDC_USE_PKCE
Add pkce settings
Get the settings from the environment
=> ✨(settings) Allow configuring PKCE for the SSO

CHANGELOG.md, src/backend/core/tests/test_api_config.py, src/backend/impress/settings.py, src/backend/locale/cn_CN/LC_MESSAGES/django.po, src/backend/locale/es_ES/LC_MESSAGES/django.po, src/frontend/apps/e2e/__tests__/app-impress/common.ts, src/frontend/apps/impress/src/i18n/translations.json
All the spanish and chinese translations are complete on crowdin. We activate it in django settings and download all translations from crowdin
=> 🌐(i18n) add spanish and chinese

docs/env.md
Update the documentation to include the missing environment variables.
The missing environment variables are involved in the build process of the frontend image.
=> 📝(project) add missing env var to env.md

README.md, docs/env.md
So that people know how to use the PUBLISH_AS_MIT variable
=> 📝(doc) update xl packages warning

CHANGELOG.md, src/backend/pyproject.toml, src/frontend/apps/e2e/package.json, src/frontend/apps/impress/package.json, src/frontend/package.json, src/frontend/packages/eslint-config-impress/package.json, src/frontend/packages/i18n/package.json, src/frontend/servers/y-provider/package.json, src/helm/helmfile.yaml, src/helm/impress/Chart.yaml, src/mail/package.json
- 🌐(frontend) keep simple tag during export #1154
- 🐛(back) manage can-edit endpoint without created room in the ws #1152
- 🐛(frontend) fix action buttons not clickable #1162
- 🐛(frontend) fix crash share modal on grid options #1174
=> 🔖(patch) release 3.4.1

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/Bug_report.md
Update the issue template to help contributors
=> 📝(contributing) update contributing policy

.github/workflows/docker-hub.yml, src/helm/env.d/dev/values.dev-backend.yaml.gotmpl, src/helm/env.d/feature/values.dev-backend.yaml.gotmpl, src/helm/env.d/feature/values.impress.yaml.gotmpl, src/helm/helmfile.yaml
Add a special environment to prepare feature app deployment
=> ♻️(ci) add feature app environment
