suitenumerique/docs

- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/models.py
- src/backend/core/tests/templates/test_api_templates_generate_document.py
- src/frontend/apps/impress/src/features/pads/pad-tools/api/useCreatePdf.tsx
- src/frontend/apps/impress/src/features/pads/pad-tools/components/PrintToPDFButton.tsx
The endpoint `templates/[ID]/generate-document` was converting from markdown to html, but the frontend can provide the body directly in html format, so we can avoid the conversion, it will reduce the amount of data lost.
Solution:
Add body type on generate-document endpoint
to allow to choose between markdown and html.
Description...
> ♻️ add body type on generate-document endpoint

- src/frontend/apps/e2e/__tests__/app-impress/header.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/pad-editor.spec.ts
- src/frontend/apps/impress/src/features/header/Header.tsx
- src/frontend/apps/impress/src/features/pads/pad/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/pads/pad/components/BlockNoteToolbar.tsx
- src/frontend/apps/impress/src/pages/_document.tsx
Some people prefer to write in markdown, or had already written stuff in markdown, so this commit adds a button to the editor that will convert the markdown to the editor's format.
[scrnli_4_16_2024_1-07-13 PM.webm](https://github.com/numerique-gouv/impress/assets/25994652/022be9fc-86f3-418c-a439-0d5ba7818d71)
> ✨(app-impress) button editor convert from markdown

- src/frontend/apps/e2e/__tests__/app-impress/pad-create.spec.ts
- src/frontend/apps/impress/src/features/pads/pad/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/pads/pad/types.tsx
- src/frontend/apps/impress/src/features/pads/pads-create/components/CardCreatePad.tsx
- src/frontend/apps/impress/src/features/templates/template-create/components/CardCreateTemplate.tsx
- src/frontend/apps/impress/src/features/templates/template/components/TemplateEditor.tsx
- src/frontend/apps/impress/src/features/templates/template/types.tsx
- src/frontend/packages/eslint-config-impress/playwright.js
All the resources were public, we fixed that.
When a resource is public, the users can see it but not edit it. 
This PR adds a warning message to the user to tell them that the resource is not editable.
> 🐛(frontend) fix all the resources were public

- src/backend/core/api/serializers.py
- src/backend/core/tests/documents/test_api_documents_retrieve.py
- src/backend/core/tests/templates/test_api_templates_retrieve.py
- src/backend/demo/data/template/code.txt
- src/backend/demo/data/template/code_editor.json
- src/backend/demo/data/template/css.txt
- src/backend/demo/management/commands/create_demo.py
- src/frontend/apps/e2e/__tests__/app-impress/template-editor.spec.ts
- src/frontend/apps/impress/src/features/templates/template-create/api/index.ts
- src/frontend/apps/impress/src/features/templates/template-create/api/useCreateTemplate.tsx
- src/frontend/apps/impress/src/features/templates/template-create/index.ts
- src/frontend/apps/impress/src/features/templates/template/components/TemplateEditor.tsx
- src/frontend/apps/impress/src/features/templates/template/components/TemplateTools.tsx
- src/frontend/apps/impress/src/features/templates/template/types.tsx
We created the button `Duplicate template`, we do this button because a template `ìs_public` is readable but not editable.
The copy will be editable.
> ✨improve template editor

- src/frontend/apps/impress/jest.setup.ts
- src/frontend/apps/impress/src/components/Box.tsx
- src/frontend/apps/impress/src/components/TextErrors.tsx
- src/frontend/apps/impress/src/components/__tests__/Box.spec.tsx
- src/frontend/apps/impress/src/features/header/Header.tsx
- src/frontend/apps/impress/src/features/menu/Menu.tsx
- src/frontend/apps/impress/src/features/menu/MenuItems.tsx
- src/frontend/apps/impress/src/features/menu/Tooltip.tsx
- src/frontend/apps/impress/src/features/pads/pad-tools/components/PadToolBox.tsx
- src/frontend/apps/impress/src/features/pads/pad/components/PadEditor.tsx
- src/frontend/apps/impress/src/features/pads/pads-create/components/CardCreatePad.tsx
- src/frontend/apps/impress/src/features/pads/pads-panel/components/PadItem.tsx
- src/frontend/apps/impress/src/features/pads/pads-panel/components/PadList.tsx
- src/frontend/apps/impress/src/features/pads/pads-panel/components/Panel.tsx
- src/frontend/apps/impress/src/pages/404.tsx
- src/frontend/apps/impress/src/pages/pads/create.tsx
- src/frontend/apps/impress/src/utils/styleBuilder.ts
Add spacing props (margin / padding) to Box component and its inheritances.
It proposes the autocompletion.
It is bind with the Cunningham spacing system.
> 🎨Box spacing

- src/frontend/apps/impress/.env.development
- src/frontend/apps/impress/.env.production
- src/frontend/apps/impress/.env.test
- src/frontend/apps/impress/src/api/__tests__/fetchApi.test.tsx
- src/frontend/apps/impress/src/api/fetchApi.ts
- src/frontend/apps/impress/src/core/auth/useAuthStore.tsx
- src/frontend/apps/impress/src/core/conf.ts
- src/frontend/apps/impress/src/core/index.ts
- src/frontend/apps/impress/src/custom-next.d.ts
- src/frontend/apps/impress/src/features/pads/pad/stores/usePadStore.tsx
- src/frontend/apps/impress/src/features/pads/pads-panel/__tests__/PanelPads.test.tsx
- src/helm/env.d/dev/values.impress.yaml.gotmpl
Road to production.
Until now, the front had to know the url of the backend and the url of the webrtc server to communicate with them.
It is not optimal because these env var must be set at build time, it means to make it works as it is now, we need multiple docker image (1 per environment), it is not very flexible.
This PR will make the frontend environment free by determining these urls at runtime.
> 👷(CI) Frontend environment free

- .github/workflows/impress-frontend.yml
It can happen that the e2e job takes longer than 10 minutes to finish, we increase the timeout to 15 minutes to avoid the job to fail.
> 💚(CI) increase timeout e2e job

- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/factories.py
- src/backend/core/models.py
- src/backend/core/tests/documents/test_api_documents_retrieve.py
- src/backend/core/tests/test_api_document_versions.py
- src/backend/core/tests/test_models_documents.py
- src/frontend/apps/e2e/__tests__/app-impress/pad-editor.spec.ts
- src/frontend/apps/impress/src/features/pads/pad/api/useUpdatePad.tsx
- src/frontend/apps/impress/src/features/pads/pad/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/pads/pad/hook/useSavePad.tsx
- src/frontend/apps/impress/src/features/pads/pad/stores/usePadStore.tsx
- src/frontend/apps/impress/src/features/pads/pad/types.tsx
- src/frontend/apps/impress/src/features/pads/pad/utils.ts
- src/frontend/apps/impress/src/features/pads/pads-create/api/useCreatePad.tsx
- src/frontend/apps/impress/src/pages/pads/[id].tsx
This PR manage the persistance of the documents.
We save the documents in different ways:
- when the user close the tab or the browser
- when the user leave the page (go to another pad by example)
- every 1 minute
----
- We save the documents only if the pad has been modified.
- Documents are collaborative, to not save multiple times the same pad, we save the pad only if the user is the last to have modified the pad.
----
Because of the collaborative aspect of the pads, the best way to store our pad is to save the Y.Doc, to do so the recommended way is to convert the Y.Doc to a Uint8Array and then to a string (base64). 
Our pad are saved as a string in a object in a Minio bucket.
> ✨(frontend) persistance-documents

- CHANGELOG.md
- Makefile
- README.md
- docker-compose.yml
- src/frontend/Dockerfile
🐋Dockerize the frontend development environment to make it easy to display the frontend development environment in the browser.
We don't mix it with the command `make run` to let it kind of optional to run the frontend in a docker container. 
We let it optional because the hot reload doesn't work well in the docker container (only windows ?) 
So, we let the developer decide to run the frontend in a docker container or not.
As before:
`make bootstrap`
Then go to: http://localhost:3000
> Docker impress dev

- .github/workflows/impress.yml
- CHANGELOG.md
- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/migrations/0002_create_pg_trgm_extension.py
- src/backend/core/tests/test_api_users.py
- src/backend/demo/management/commands/create_demo.py
- src/backend/demo/tests/test_commands_create_demo.py
- src/frontend/apps/impress/src/core/auth/api/types.ts
- src/frontend/apps/impress/src/features/pads/pad-editor/components/BlockNoteEditor.tsx
We need to be able to research users to invite them.
This PR add the route GET `/api/v1.0/users/`.
2 query params are available:
- `q` to search on `email` field
- `document_id` to exclude user that have access to a `document_id`
> ✨(backend) search users

- .github/workflows/impress-frontend.yml
- CHANGELOG.md
⚡️(CI) improve docker build cache
Improve the caching by using docker buildx, it should speed up the build process by using the cache from the previous build.
> ⚡️Cache docker e2e

- src/backend/core/models.py
- src/backend/core/tests/test_models_documents.py
We will need to store more than a file for a document in object storage: multiple languages, images, etc.
For this reason, the document ID should be a folder and the content a file should be stored in this folder.
Store document content in object storage under a folder named by the document ID. I propose to call the content file:
`{document.id}/file`.
Thus we will be able to store the documents' images under an `images` subfolder for example:
`{document.id}/images/{image.id}`
> ♻️(documents) store document file in object storage in a folder

- src/frontend/apps/e2e/__tests__/app-impress/doc-panel.spec.ts
Multiple page.goto can cause flakiness.
An page.goto is already called in the beforeEach, so we don't need to call it again in the test.
> ⚡️(e2e) remove unnecessary page.goto

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/package.json
- src/frontend/apps/y-webrtc-signaling/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-impress/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.impress.yaml.gotmpl
- src/helm/env.d/production/values.impress.yaml.gotmpl
- src/mail/package.json
- src/tsclient/package.json
🔖(major) major release to 1.0.0
- 🛂(frontend) Manage the document's right (#75) 
- ✨(frontend) Update document (#68)
- ✨(frontend) Remove document (#68)
- 🐳(docker) dockerize dev frontend (#63)
- 👔(backend) list users with email filtering (#79)
- ✨(frontend) add user to a document (#52)
- ✨(frontend) invite user to a document (#52)
- 🛂(frontend) manage members (update role / list / remove) (#81)
- ✨(frontend) offline mode (#88)
- 🌐(frontend) translate cgu (#83)
- ✨(service-worker) offline doc management (#94)
- ⚗️(frontend) Add beta tag on logo (#121)
- ♻️(frontend) Change site from Impress to Docs (#76)
- ✨(frontend) Generate PDF from a modal (#68)
- 🔧(helm) sticky session by request_uri for signaling server (#78)
- ♻️(frontend) change logo (#84)
- ♻️(frontend) pdf has title doc (#84)
- …
> 🔖(major) major release to 1.0.0

- src/frontend/apps/impress/src/features/service-worker/ApiPlugin.ts
We now display the creation and modification date of the document in the document grid, so when we create a new document in offline mode we need to set the dates as well.
> 👔(service-worker) add new field to create doc

- CHANGELOG.md
- src/frontend/apps/impress/src/components/SideModal.tsx
Create SideModal component for displaying modal on the side of the screen.
This component is build above the Cunningham component, so all the cunnighama props are still available.
This component can be used on the left or the right side.
[scrnli_7_8_2024_4-31-06 PM.webm](https://github.com/numerique-gouv/impress/assets/25994652/dcd014b2-e05a-4f03-9c16-c56b7604f31d)
> ✨(frontend) create side modal component

- .github/workflows/impress-frontend.yml
- .github/workflows/impress.yml
- CHANGELOG.md
- docker-compose.yml
- src/frontend/apps/e2e/__tests__/app-impress/common.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-create.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-grid.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-member-grid.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-tools.spec.ts
- src/frontend/apps/impress/src/components/SideModal.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGrid.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridActions.tsx
Add document action buttons to the document grid:
[scrnli_7_9_2024_11-32-02 AM.webm](https://github.com/numerique-gouv/impress/assets/25994652/446829a0-b965-45d6-bf78-7e766ffb5205)
> ✨Doc grid actions

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-tools.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-header/components/ModalPDF.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/utils.ts
A recent update from Blocknote provides us the alignment, the color and the background color of the different editor texts. 
We adapt our converter to adapt these new features to the pdf.
> 🎨(frontend) better conversion editor to pdf

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-grid.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/components/DocEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/Panel.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGrid.tsx
- src/frontend/apps/impress/src/layouts/MainLayout.tsx
The app was limiting the layout height to the screen size, which was a bit annoying when the content was bigger than the screen. We stop doing that, and now the layout will grow as needed.
> 🎨(frontend) stop limit layout height to screen size

- CHANGELOG.md
- src/backend/core/models.py
- src/backend/core/tests/test_models_invitations.py
- src/backend/impress/settings.py
- src/helm/env.d/preprod/values.impress.yaml.gotmpl
- src/helm/env.d/production/values.impress.yaml.gotmpl
- src/helm/env.d/staging/values.impress.yaml.gotmpl
- src/mail/mjml/invitation.mjml
Email settings were wrongly configured. It leed to unsent email and timeout response from the backend server. 
This PR fixes the issue by enabling SSL when sending email.
> 🐛(backend) enable SSL when sending email

- .github/workflows/impress-frontend.yml
- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/auth.setup.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-version.spec.ts
- src/frontend/apps/e2e/package.json
- src/frontend/apps/e2e/playwright.config.ts
To speed up pull request flow, put e2e tests only mandatory for Chrome.
Chrome is the fastest and more reliable browser with the e2e tests.
We still test Firefox and Webkit, but they are not mandatory.
They will still have to be checked regularly, to discern the flaky test with the one showing a bug.
Extra attention during the deployment phase.
> ⚡️(CI) only e2e chrome mandatory

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/package.json
- src/frontend/apps/y-webrtc-signaling/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-impress/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.impress.yaml.gotmpl
- src/helm/env.d/production/values.impress.yaml.gotmpl
- src/mail/package.json
- 🎨(frontend) better conversion editor to pdf #151
- ✨Export docx (word) #161
- 🌐Internationalize invitation email #167
- ✨(frontend) White branding #164
- ✨Email invitation when add user to doc #171
- ✨Invitation management #174
- 🐛(y-webrtc) fix prob connection #147
- ⚡️(frontend) improve select share stability #159
- 🐛(backend) enable SSL when sending email #165
- 🎨(frontend) stop limit layout height to screen size #158
- ⚡️(CI) only e2e chrome mandatory #177
- 🔥(helm) remove htaccess #181
----
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.1.0...v1.2.0
> 🔖(minor) release to 1.2.0

- CHANGELOG.md
- src/backend/core/api/viewsets.py
- src/backend/core/tests/documents/test_api_documents_list.py
- src/frontend/apps/e2e/__tests__/app-impress/doc-grid.spec.ts
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGrid.tsx
The datagrid is now ordered by updated_at desc.
> ♻️ Change ordering datagrid

- CHANGELOG.md
- src/backend/core/api/serializers.py
- src/backend/core/api/utils.py
- src/backend/core/api/viewsets.py
- src/backend/core/models.py
- src/backend/core/tests/documents/test_api_documents_attachment_upload.py
- src/backend/core/tests/documents/test_api_documents_retrieve.py
- src/backend/core/tests/documents/test_api_documents_retrieve_auth.py
- src/backend/core/tests/test_models_documents.py
- src/backend/impress/settings.py
- src/backend/pyproject.toml
- src/helm/env.d/dev/values.impress.yaml.gotmpl
- src/helm/env.d/preprod/values.impress.yaml.gotmpl
- src/helm/env.d/production/values.impress.yaml.gotmpl
- src/helm/env.d/staging/values.impress.yaml.gotmpl
- src/helm/impress/templates/ingress_media.yaml
- src/helm/impress/templates/media_svc.yaml
- src/helm/impress/values.yaml
We want to be able to attach images to a document. Strict access control should be applied on all images of a document.
- upload images to a folder next to each document's content file : `{document.id}/attachments/{image_filename}
- allow downloading attachment images from object storage via the nginx ingress. Access control is done thanks to nginx subrequests.
- Update the helm chart to add the new media url with access control delegated to Django
> Add image upload and download from media url

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteToolbar.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/useSaveDoc.tsx
🔥(frontend) remove saving modal
The saving toast are removed.
Users were complaining about the toast that was shown when saving a document.
----
🔥(frontend) hide markdown button if not text
If we are selected a block that is not a text block, we hide the markdown button.
> 🔥(frontend) remove markdown button

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
The "code" was not visible on the editor because the background was too light.
The background color was darkened to `make` the "code" more visible.
> 💄(frontend) code background darkened on editor

- src/helm/env.d/preprod/values.impress.yaml.gotmpl
- src/helm/env.d/production/values.impress.yaml.gotmpl
- src/helm/env.d/staging/values.impress.yaml.gotmpl
There is no mechanism to have the media storage URL from a secret from the ingress.
The media storage URL has to be hardcoded.
We replace the media storage URL in the ingress, if we change the cluster, we will have to update these urls.
> 🔧(helm) replace storage url in ingressMedia

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-version.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/components/DocEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/useSaveDoc.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/index.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/stores/useDocStore.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocHeader.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/ModalVersion.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/Panel.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/VersionItem.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/index.ts
- src/frontend/apps/impress/src/features/docs/doc-versioning/index.ts
- src/frontend/apps/impress/src/features/docs/doc-versioning/stores/index.ts
- src/frontend/apps/impress/src/features/docs/doc-versioning/stores/useDocVersionStore.tsx
We refacto the way to display the version. 
We add a confirmation modal.
[scrnli_9_2_2024_5-01-45 PM.webm](https://github.com/user-attachments/assets/5e0f859e-0cde-4ce8-972a-9310fd1e1f4a)
> ♻️Improve versioning

- CHANGELOG.md
- Dockerfile
- src/frontend/apps/e2e/__tests__/app-impress/doc-version.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-summary/components/Summary.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/VersionList.tsx
The emoticon were not exported in the PDF.
> 🐛 Fix emoticon in pdf export

- CHANGELOG.md
- docker-compose.yml
Forcing `platform: linux/amd64` for the PostgreSQL image causes compatibility issues and performance
degradation on Mac ARM chips (M1/M2).
Removing the platform specification allows Docker
to select the appropriate architecture automatically, ensuring better performance and compatibility.
> 🔧(compose) stop forcing platform for Keycloak PostgreSQL image

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-create.spec.ts
- src/frontend/apps/impress/src/pages/_app.tsx
- src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
We update the meta title for the docs page with the title of the document.
It will be easier for the user to identify the document in their browser tab, in their bookmarks and history.
> ✨(frontend) update meta title for docs page

- src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
The meta title is not displayed when we come back to a page from the dynamic router. The code seems to
compute to quickly so we need to add a delay to the meta title computation.
> 🐛(frontend) meta title rerender issue

- CHANGELOG.md
- Makefile
docker build frontend dev was lacking.
If dependencies were updated, the change were
not reflected in the frontend container.
> 🧑‍💻(makefile) add build frontend dev

- src/helm/impress/templates/secrets.yaml
When new secret is added to backend secret, it's not sync at the beginning of argocd synchronisation and jobs are blocked. Theses new annotations fix this issue.
> 🔒️(helm) fix secret sync precedence

- CHANGELOG.md
- src/backend/core/authentication/backends.py
- src/backend/core/tests/authentication/test_backends.py
Gitlab oidc was failing.
It is failing because the userinfo endpoint can return 2 content types:
- application/json
- application/jwt
https://github.com/numerique-gouv/impress/blob/53267c783a0b47b15025dc0d211d2a77a345de8a/src/backend/core/authentication/backends.py#L45-L51
Gitlab oidc returns a json object, while Agent Connect oidc returns a jwt token.
We are adapting the authentication to handle both cases.
----
⚠️ The logout does not seem to work with the Gitlab oidc. I suggest we open an issue, maybe you will want to dig more on that @securitykernel ?
> 🐛 (backend) gitlab oicd userinfo endpoint

- .github/workflows/impress.yml
- src/backend/core/tests/test_models_templates.py
- ✅(backend) fix flaky test on tmp file: 
It seems to have a race condition, sometimes the tmp file is not deleted before the test assertion.  We let the test sleep for 0.5 second before the assertion.
- ✅(CI) fix flaky test on Minio initialized:
Minio server need to be initialized before running the job to configure Minio.
We add a delay to wait for Minio server to be ready.
> ✅(backend) fix flaky tests

- CHANGELOG.md
- src/frontend/apps/impress/src/components/TextErrors.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
When we were uploading a file that was not allowed, an error alert was shown. This alert was not closeable. This commit makes the alert closeable.
> 💄(frontend) error alert closeable on editor

- CHANGELOG.md
- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/models.py
- src/backend/core/tests/documents/test_api_document_versions.py
- src/backend/core/tests/test_models_documents.py
Getting versions was not working properly. Some versions returned were not accessible by the user requesting the list of available versions.
We refactor the code to make it simpler and let the frontend handle pagination (load more style).
> ♻️(api) refactor getting versions to expose pagination

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/common.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-routing.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-visibility.spec.ts
- src/frontend/apps/impress/src/core/AppProvider.tsx
- src/frontend/apps/impress/src/core/auth/Auth.tsx
- src/frontend/apps/impress/src/core/auth/useAuthStore.tsx
- src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
When we access a private doc and we are not connected we were getting an error message.
Instead of this error message, we now redirect to the OIDC.
> 🛂(frontend) redirect to the OIDC when private doc and unauthentified

- .github/workflows/docker-hub.yml
- CHANGELOG.md
- Dockerfile
- src/frontend/Dockerfile
Add a security scan for CVE with trivy
> ✨(ci) add security scan

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/common.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-member-list.spec.ts
- src/frontend/apps/impress/src/components/Box.tsx
- src/frontend/apps/impress/src/cunningham/cunningham-style.css
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/components/DocVisibility.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/components/ModalShare.tsx
- src/frontend/apps/impress/src/features/docs/doc-table-content/components/TableContent.tsx
- src/frontend/apps/impress/src/features/docs/members/invitation-list/components/InvitationItem.tsx
- src/frontend/apps/impress/src/features/docs/members/invitation-list/components/InvitationList.tsx
- src/frontend/apps/impress/src/features/docs/members/members-add/components/AddMembers.tsx
- src/frontend/apps/impress/src/features/docs/members/members-add/components/SearchUsers.tsx
- src/frontend/apps/impress/src/features/docs/members/members-list/components/MemberItem.tsx
- src/frontend/apps/impress/src/features/docs/members/members-list/components/MemberList.tsx
- src/frontend/package.json
- src/frontend/yarn.lock
Readers and editors of a document can access the share modal and see the list of members and their roles.
[scrnli_10_3_2024_3-33-20 PM.webm](https://github.com/user-attachments/assets/22765b45-1d64-4b7d-a513-ac79c9c1599e)
> 🛂(frontend) Readers and editors can access share modal

- CHANGELOG.md
- src/backend/core/authentication/backends.py
- src/backend/core/tests/authentication/test_backends.py
- src/backend/impress/settings.py
Some OIDC identity providers may provide a random value in the "sub" field instead of an identifying ID. In this case, it may be a good idea to fallback to matching the user on its email field.
- Add a setting `OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION` which defaults to `True`
- When logging-in, if the sub does not match any existing user, try matching on the `email` field before creating a new user for the unknown sub.
> 🛂(backend) match email if no existing user matches the sub

- src/frontend/apps/impress/src/features/service-worker/ApiPlugin.ts
When we were installing the service-worker, errors were thrown because of circular imports.
This commit fixes the problem by being more explicit about the imports.
> 🐛(service-worker) fix circular import problem

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-impress/package.json
- src/frontend/packages/i18n/package.json
- src/frontend/servers/y-provider/package.json
- src/helm/env.d/preprod/values.impress.yaml.gotmpl
- src/helm/env.d/production/values.impress.yaml.gotmpl
- src/mail/package.json
- ✨(backend) add name fields to the user synchronized with OIDC #301
- ✨(ci) add security scan #291
- ♻️(frontend) Add versions #277
- ✨(frontend) one-click document creation #275
- ✨(frontend) edit title inline #275
- 📱(frontend) mobile responsive #304
- 🌐(frontend) Update translation #308
- 💄(frontend) error alert closeable on editor #284
- ♻️(backend) Change email content #283
- 🛂(frontend) viewers and editors can access share modal #302
- ♻️(frontend) remove footer on doc editor #313
- 🛂(frontend) match email if no existing user matches the sub
- 🐛(backend) gitlab oicd userinfo endpoint #232
- 🛂(frontend) redirect to the OIDC when private doc and unauthentified #292
- ♻️(backend) getting list of document versions available for a user #258
- 🔧(backend) fix configuration to avoid …
> 🔖Release 1.5.0

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/members/members-add/components/AddMembers.tsx
- src/frontend/apps/impress/src/features/docs/members/members-add/components/SearchUsers.tsx
- src/frontend/apps/impress/src/features/docs/members/members-add/index.ts
- src/frontend/apps/impress/src/features/docs/members/members-list/api/useDeleteDocAccess.ts
When we remove a user from the list of members, we need to invalidate the user query for the user to be found again.
We improve the error message when a user is already a member of the document.
> 🐛(frontend) invalidate queries after removing user

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
> ✨(frontend): Added copy-as buttons for HTML and Markdown

- CHANGELOG.md
- Dockerfile
- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/tests/documents/test_api_documents_attachment_upload.py
- src/backend/impress/settings.py
- src/backend/pyproject.toml
We want to allow users to upload files to a document, not just images. 
We try to enforce coherence between the file extension and the real mime type of its content using magic.
If a file is deemed unsafe, it is still accepted during upload and the information is stored as metadata on the object for display to readers in the frontend.
> ♻️(backend) allow uploading more types of attachments

- CHANGELOG.md
- Makefile
- docker-compose.yml
This will fix [issue #339](https://github.com/numerique-gouv/impress/issues/339), ensuring that nginx starts only after app-dev is up and running, preventing startup failures.
To address this, the following steps will be taken:
- Update docker-compose.yml to include a dependency on nginx for app-dev.
- Verify that the dependency order resolves the issue with nginx startup.
Description...
> 🐛(backend) Fixing docker-compose.yml to make nginx depend on app-dev

- CHANGELOG.md
- src/backend/core/authentication/backends.py
- src/backend/core/tests/authentication/test_backends.py
When a user is disabled and tries to login, we don't want the user to be duplicated, the user should not be able to login.
Fixes https://github.com/numerique-gouv/impress/issues/324
> 🛂(backend) do not duplicate user when disabled

- CHANGELOG.md
- CONTRIBUTING.md
Add a CONTRIBUTING.md file to the project root to help new contributors understand how to contribute to the project.
See: https://github.com/numerique-gouv/impress/blob/c518e46bafa7747673f84d71ef919ca926acbb3e/CONTRIBUTING.md
> 📝(docs) add CONTRIBUTING.md doc

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/MarkdownButton.tsx
Currently, when you change language the editor does not change. So we add this functionality
I suggest we use the default translations already offered by blocknotejs and reload the editor whenever a new language is selected.
close #271
> 🌐(frontend) add localization to editor

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/common.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-member-list.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-visibility.spec.ts
- src/frontend/apps/impress/cunningham.ts
- src/frontend/apps/impress/src/components/Box.tsx
- src/frontend/apps/impress/src/components/Text.tsx
- src/frontend/apps/impress/src/cunningham/cunningham-style.css
- src/frontend/apps/impress/src/cunningham/cunningham-tokens.css
- src/frontend/apps/impress/src/cunningham/cunningham-tokens.ts
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocTitle.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/components/DocVisibility.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/components/ModalShare.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/types.tsx
- src/frontend/apps/impress/src/features/service-worker/ApiPlugin.ts
We increased the visibility options for docs:
- public
- restricted
- authenticated
We also have 2 editability options:
- readonly
- editable
The editability options are only available for public and authenticated docs.
[scrnli_VZHQd70DS9qxw9.webm](https://github.com/user-attachments/assets/48fb17ca-933c-4ccc-8b23-186bf8240db4)
> ✨Public and restricted doc editable

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/components/AIButton.tsx
To display the throttle error messages, we are doing a condition on the error message that we get from the backend.
It is error prone because the backend error message are internationalized.
It fix partially this issue: #373
> ♻️(frontend) improve handleAIError

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-routing.spec.ts
- src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
Some documents are available publicly (without being logged) and may thus end-up being indexed by search engine.
Add a meta tag in the <head> section of the page (See https://developers.google.com/search/docs/crawling-indexing/block-indexing for more information):
```
<meta name="robots" content="noindex">
```
> 🐛(frontend) avoid documents indexing in search engine

- CHANGELOG.md
- src/backend/core/models.py
- src/backend/core/tests/documents/test_api_documents_retrieve.py
- src/backend/core/tests/templates/test_api_templates_retrieve.py
- src/backend/core/tests/test_models_documents.py
- src/backend/core/tests/test_models_templates.py
- src/frontend/apps/e2e/__tests__/app-impress/common.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-grid.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-visibility.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-header/types.ts
- src/frontend/apps/impress/src/features/docs/doc-management/components/ModalShare.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/types.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/utils.ts
- src/frontend/apps/impress/src/features/docs/members/invitation-list/components/InvitationItem.tsx
- src/frontend/apps/impress/src/features/docs/members/members-add/components/AddMembers.tsx
- src/frontend/apps/impress/src/features/docs/members/members-list/components/MemberItem.tsx
- src/frontend/apps/impress/src/features/service-worker/ApiPlugin.ts
The frontend is lacking information whether it should try to display a document specific accesses when opening the "Share" menu.
> ✨(backend) add new ability on document "accesses_view"

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-impress/package.json
- src/frontend/packages/i18n/package.json
- src/frontend/servers/y-provider/package.json
- src/mail/package.json
- 📝Contributing.md #352
- 🌐(frontend) add localization to editor #368
- ✨Public and restricted doc editable #357
- ✨(frontend) Add full name if available #380
- ✨(backend) Add view accesses ability #376
- ♻️(frontend) list accesses if user has abilities #376
- ♻️(frontend) avoid documents indexing in search engine #372
- 👔(backend) doc restricted by default #388
- 🐛(backend) require right to manage document accesses to see invitations #369
- 🐛(i18n) same frontend and backend language using shared cookies #365
- 🐛(frontend) add default toolbar buttons #355
- 🐛(frontend) throttle error correctly display #378
- 🔥(helm) remove infra related codes #366
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.6.0...v1.7.0
> 🔖(minor) release 1.7.0

- CHANGELOG.md
- src/backend/core/api/viewsets.py
- src/backend/core/tests/test_api_users.py
In some edge cases, the domain part the email addresse is longer than the name part. Users searches by email similarity then return a lot of unsorted results.
At the moment, we still think it is good to propose results with a weak similarity on the name part because we want to avoid as much as possible creating duplicate users by inviting one of is many emails, a user who is already in our database.
Fixes #399
> 🚸(backend) improve users similarity search and sort results

- CHANGELOG.md
- src/backend/core/models.py
Some sub have comma, the regex was a bit too strict and didn't allow it, this PR fixes that.
> 🦺(backend) add comma to sub regex

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
When the user was in read-only mode, the user tag could be displayed when they were touching the doc. 
This PR fixes this issue.
We add the full name instead of the email in the cursor tag.
> 🐛(editor) collaborative user tag hidden when read only

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-editor/components/AIButton.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/DocEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/stores/index.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/utils.ts
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocTitle.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/ModalExport.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/api/useUpdateDocLink.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/index.ts
- src/frontend/apps/impress/src/features/docs/doc-management/stores/index.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/stores/useDocStore.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/utils.ts
- src/frontend/apps/impress/src/features/docs/doc-table-content/components/TableContent.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/ModalVersion.tsx
- src/frontend/apps/impress/src/features/docs/members/members-add/api/useCreateDocAccess.tsx
- src/frontend/apps/impress/src/features/docs/members/members-list/api/useDeleteDocAccess.ts
- src/frontend/apps/impress/src/features/docs/members/members-list/api/useUpdateDocAccess.ts
- src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
- src/frontend/apps/impress/src/stores/index.ts
- src/frontend/apps/impress/src/stores/useBroadcastStore.tsx
Add the useBroadcastStore.
It will give us the ability to easily broadcast actions to all connected clients.
In this case, we needed to requery the doc to everyone when a change relative to the doc rights was made.
Add any tasks:
```ts
const { setBroadcastProvider, addTask } = useBroadcastStore();
setBroadcastProvider(newProvider);
addTask(`hello`, () => {
console.log("Hello world");
});
```
Broadcast it to everyone:
```ts
const { broadcast } = useBroadcastStore();
broadcast(`hello`);
// console.log("Hello world") will be displayed to every users
```
2 different users, 1 on Chrome, the second on Firefox:
[scrnli_LZyuCI7HRjg5zv.webm](https://github.com/user-attachments/assets/2391477b-e653-464a-bc94-17014bbc64e7)
> ✨(frontend) add useBroadcastStore

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/DocEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/PanelEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/stores/index.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/stores/useEditorStore.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/ModalExport.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/stores/useDocStore.tsx
- src/frontend/apps/impress/src/features/docs/doc-table-content/components/TableContent.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/ModalVersion.tsx
- src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
We re-organized and simplify some stores.
> ♻️(frontend) simplify stores

- CHANGELOG.md
- src/backend/impress/settings.py
In a Kubernetes environment, we need to whitelist the pod's IP address to allow health checks to pass. This ensures that Kubernetes liveness and readiness probes can access the application to verify its health.
Based on this commit: https://github.com/numerique-gouv/meet/commit/d965ee706014b6395fdb2d2ce0f3e4f520f64503
> 🔒️(backend) whitelist the pod's IP address

- .github/workflows/docker-hub.yml
- CHANGELOG.md
Trivy is extremly flaky, we need to continue on error to avoid blocking the pipeline.
We still keep the check, to see if there are any vulnerabilities, but we don't want to block the pipeline.
> ✅(CI) trivy continue on error

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocTitle.tsx
- src/frontend/apps/impress/src/services/Crisp.tsx
Small fixes from the review of on preproduction of the version 1.8.0.
> 🩹 Fine tuning 1.8.0

- CHANGELOG.md
- src/frontend/apps/impress/package.json
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/index.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/useUploadFile.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/ModalExport.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/components/ModalRemoveDoc.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/components/ModalShare.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/ModalVersion.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/VersionItem.tsx
- src/frontend/yarn.lock
At the base, this code was made to solve this issue: https://github.com/numerique-gouv/impress/issues/384
The link in the read mode was not clickable anymore, it was due to a attempt to not display the cursor of anonymous users.
We changes the way to do it by rendering our own cursor, when a user is anonymous we don't render the cursor.
By rendering our own cursor we fixed another problem, the cursor was flickering when the user was typing at the end of the line on the firefox browser.
https://github.com/TypeCellOS/BlockNote/blob/3ef72187c6c10fbc37891d922b4ed6421474482b/packages/core/src/editor/BlockNoteExtensions.ts#L261-L262
Initially:
https://github.com/yjs/y-prosemirror/blob/df4257b499bf25b2b8e69d56cc2d8bb790f8e7ba/src/plugins/cursor-plugin.js#L39
We are investigating the purpose of …
> 🐛(frontend) link not clickable and flickering firefox

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-grid.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-management/api/useDocs.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/types.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGrid.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LefPanelTargetFilters.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanel.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelContent.tsx
- src/frontend/apps/impress/src/pages/docs/index.tsx
- Introduced a new enum for default document filters to improve code clarity.
- Updated the API call to support filtering documents based on the creator.
- Enhanced the DocsGrid component to accept a target filter, allowing dynamic content rendering based on user selection.
- Modified the main layout to include a left panel for improved navigation and user experience.
- Added a new test suite for document filters, verifying the visibility and selection states of 'All docs', 'My docs', and 'Shared with me'.
https://github.com/user-attachments/assets/55457882-69ae-4df6-a7a6-4be2357a64eb
> ✨(frontend) implement document filtering

- CHANGELOG.md
- src/frontend/apps/impress/src/cunningham/cunningham-style.css
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelContent.tsx
> 🐛(frontend) fix doc grid button

- CHANGELOG.md
- src/frontend/apps/impress/src/features/header/components/Header.tsx
- src/frontend/apps/impress/src/features/header/components/Title/Title.tsx
In order to modularize and simplify customizations to components, 
the title component is encapsulated.
closes #406
> 🔨(frontend) encapsulate title component

- .github/workflows/impress-frontend.yml
- CHANGELOG.md
- env.d/development/common.dist
- src/backend/core/api/viewsets.py
- src/backend/core/tests/test_api_config.py
- src/backend/impress/settings.py
- src/frontend/apps/e2e/__tests__/app-impress/config.spec.ts
- src/frontend/apps/impress/src/core/config/api/useConfig.tsx
- src/frontend/apps/impress/src/core/config/hooks/useCollaborationUrl.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/DocEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/PanelEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/useHeadings.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocHeader.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/utils.ts
- src/frontend/apps/impress/src/features/docs/doc-table-content/components/TableContent.tsx
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/ModalVersion.tsx
The PR #472 is quite big, we split what we can to make the review as easy as possible.
> ♻️Misc refacto

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/stores/useDocStore.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/utils.ts
The initial document creation could create bug with collaboration. As soon as a char was enter and saved, this bug stopped to appear (basically after 1 mn).
The initial creation involving collaboration seems more complicated that what we were doing:
https://github.com/TypeCellOS/BlockNote/blob/71792c2fbdc99785cd8ce5b540d1a468e6c66131/packages/core/src/editor/BlockNoteTipTapEditor.ts#L73-L131
We will let Blocknote managing the initial creation, and we will update the Blocknote initial creation with our initial creation. 
Collaborating issue are gone, the document sync correctly between collaborators.
> 🐛(frontend) fix initial content with collaboration

- CHANGELOG.md
- src/frontend/servers/y-provider/__mocks__/mock.js
- src/frontend/servers/y-provider/__tests__/server.test.ts
- src/frontend/servers/y-provider/jest.config.js
- src/frontend/servers/y-provider/package.json
- src/frontend/servers/y-provider/src/routes.ts
- src/frontend/servers/y-provider/src/server.ts
- src/frontend/servers/y-provider/src/utils.ts
- src/frontend/yarn.lock
Allow backend service to convert markdown content in yjs one using a nodejs microservice bootstrapped by @AntoLC for collaboration purpose.
Blocked by #472 
Please check my commits;
> Mardown converter endpoint

- .github/workflows/impress-frontend.yml
In a recent commit we removed Chrome from the install of playwright in the CI job test-e2e, but it is needed, we put it back.
> 🐛(CI) add chrome playwright install

- env.d/development/common.e2e.dist
- src/frontend/apps/e2e/__tests__/app-impress/doc-create.spec.ts
We recently added a new feature to the app, which is the ability to create a document from server to server.
`Server A` will send a request to `Server B` with a markdown content, and `Server B` will create the document after converting the markdown to yjs base64 format.
This test will check all the steps of the process and assert that the document is displayed correctly on the frontend in the blocknote editor.
> ✅(e2e) add a test on doc creation server side

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-impress/package.json
- src/frontend/packages/i18n/package.json
- src/frontend/servers/y-provider/package.json
- src/helm/extra/Chart.yaml
- src/helm/helmfile.yaml
- src/helm/impress/Chart.yaml
- src/mail/package.json
- ✨(backend) add server-to-server API endpoint to create documents #467
- ✨(email) white brand email #412
- ✨(y-provider) create a markdown converter endpoint #488
- ⚡️(docker) improve y-provider image #422
- ⚡️(e2e) reduce flakiness on e2e tests #511
https://github.com/TypeCellOS/BlockNote/releases/tag/v0.21.0
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v1.9.0...v1.10.0
> 🔖(minor) release 1.10.0

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-favorite.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-grid.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-management/api/index.ts
- src/frontend/apps/impress/src/features/docs/doc-management/api/useCreateFavoriteDoc.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/api/useDeleteFavoriteDoc.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/api/useDocs.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/assets/pinned-document.svg
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridActions.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridItem.tsx
- src/frontend/apps/impress/src/features/header/components/Header.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanel.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelContent.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelFavorites.tsx
- src/frontend/apps/impress/src/features/left-panel/stores/useLeftPanelStore.tsx
- Introduced `useMakeFavoriteDoc` and `useRemoveFavoriteDoc` hooks for managing favorite documents.
- Updated `DocsGridActions` to allow users to pin/unpin documents.
- Enhanced `useDocs` API to support filtering by favorite status.
- Modified `DocsGridItem` to visually indicate pinned documents.
- Adjusted SVG asset for the pinned document icon.
- Refactored `LeftPanelContent` and `LeftPanel` components for improved layout and functionality.
> ✨(frontend) add favorite document functionality

- CHANGELOG.md
- src/helm/impress/templates/ingress.yaml
- src/helm/impress/templates/ingress_admin.yaml
- src/helm/impress/templates/ingress_collaboration_api.yaml
- src/helm/impress/templates/ingress_collaboration_ws.yaml
- src/helm/impress/templates/ingress_media.yaml
- src/helm/impress/values.yaml
This merge requests sets an option for those who uses impress with a different secretName in ingress.
This defaults does not change the current deployments.
> 🔧(helm) add option to disable default tls setting

- src/frontend/apps/impress/src/stores/useSentryStore.tsx
- src/frontend/servers/y-provider/src/services/sentry.ts
reduce `tracesSampleRate` due to +120k daily events on the shared sentry instance
> fix(sentry): reduce tracesSampleRate

- CHANGELOG.md
- src/backend/core/authentication/backends.py
- src/backend/core/tests/authentication/test_backends.py
- src/backend/impress/settings.py
We want to be able to refuse connection for users who have missing claims from a list of required keys.
Add option to configure list of required OIDC claims: USER_OIDC_REQUIRED_CLAIMS.
Defaults to an empty list.
> ✨(backend) add option to configure list of required OIDC claims

- src/helm/helmfile.yaml
- src/helm/impress/Chart.yaml
- src/helm/impress/README.md
- src/helm/impress/generate-readme.sh
- src/helm/impress/templates/backend_deployment.yaml
- src/helm/impress/templates/frontend_deployment.yaml
- src/helm/impress/templates/yprovider_deployment.yaml
- src/helm/impress/values.yaml
We need to be abble to add specific annotations on Deployment in order to use a reloader when external-secret sync new secrets
> 🔧(helm) add option to configure deployment annotations

- CHANGELOG.md
- src/backend/core/authentication/backends.py
- src/backend/core/tests/authentication/test_backends.py
- src/backend/impress/settings.py
It was [pointed by @lebaudantoine](https://github.com/numerique-gouv/impress/pull/525/files) that the OIDC specification uses the term "essential claims" for what we called "required claims".
Further more, the Mozilla OIDC library that we use, validates claims in a method called "verify_claims".
Let's do it in the same method by overriding it.
> ♻️(backend) rename required claims to essential claims as per spec

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-visibility.spec.ts
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGrid.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelHeader.tsx
Currently, if the user is not logged in and goes to a public document, they can create or search for documents
We must therefore hide these buttons if we are not connected
> ✨(frontend) hide search and create doc button if not logged

- CHANGELOG.md
- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
3 requests we able to create a document:
- POST document
- GET collaboration-auth
- GET media-auth
If the 2 last were faster than the first, a document was created without the necessary informations.
> 🐛(backend) race condition creation issue

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-member-create.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-visibility.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocHeader.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/hooks/index.ts
- src/frontend/apps/impress/src/features/docs/doc-management/hooks/useCopyDocLink.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModal.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModalFooter.tsx
- src/frontend/apps/impress/src/features/docs/doc-table-content/components/Heading.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridActions.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridItem.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridItemSharedButton.tsx
- src/frontend/apps/impress/src/hook/index.ts
- src/frontend/apps/impress/src/hook/useClipboard.tsx
Currently, the sharing method is shown even though we do not have the rights. We remove this possibility by adding a button to copy the links
> 🐛(frontend) the share modal is shown when you don't have the abilities 

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
- src/frontend/apps/impress/package.json
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/yarn.lock
The last version of Blocknote (0.22.0) has a bug, when we copy paste a title, the app sometimes crashes.
Better to downgrade to 0.21.0 until the bug is fixed.
[scrnli_ua654412lK69jG.webm](https://github.com/user-attachments/assets/b40cb314-7f5e-4953-8703-a8709bbb6c35)
> 🐛(frontend) title copy break app

- CHANGELOG.md
- docker-compose.yml
- src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-member-create.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-visibility.spec.ts
- src/frontend/apps/impress/src/components/DropdownMenu.tsx
- src/frontend/apps/impress/src/components/Link.tsx
- src/frontend/apps/impress/src/cunningham/cunningham-style.css
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocHeader.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModal.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModalFooter.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModalInviteUserByEmail.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocVisibility.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/hooks/useTranslatedShareSettings.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGrid.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridActions.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridItem.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridItemSharedButton.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/SimpleDocItem.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/hooks/useResponsiveDocGrid.tsx
- src/frontend/apps/impress/src/pages/globals.css
Several feedbacks were given on the understanding of document sharing. We have simplified it to allow users to see the sharing status of a document and make it clearer the number of people invited
> 💄(frontend) add abilitie on doc row

- CHANGELOG.md
- docs/examples/impress.values.yaml
- src/backend/core/api/viewsets.py
- src/backend/core/tests/test_api_config.py
- src/backend/impress/settings.py
- src/frontend/apps/e2e/__tests__/app-impress/config.spec.ts
- src/frontend/apps/impress/package.json
- src/frontend/apps/impress/src/core/config/ConfigProvider.tsx
- src/frontend/apps/impress/src/core/config/api/useConfig.tsx
- src/frontend/apps/impress/src/services/Posthog.tsx
- src/frontend/apps/impress/src/services/index.ts
- src/frontend/yarn.lock
- src/helm/env.d/dev/values.impress.yaml.gotmpl
- src/helm/impress/Chart.yaml
- src/helm/impress/README.md
- src/helm/impress/templates/_helpers.tpl
- src/helm/impress/templates/ingress_posthog.yaml
- src/helm/impress/templates/ingress_posthog_assets.yaml
- src/helm/impress/templates/posthog_assets_svc.yaml
- src/helm/impress/templates/posthog_svc.yaml
- src/helm/impress/values.yaml
We integrate posthog, it will help us to track user behavior and improve the product.
> 📈Integrate Posthog

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-impress/package.json
- src/frontend/packages/i18n/package.json
- src/frontend/servers/y-provider/package.json
- src/helm/helmfile.yaml
- src/helm/impress/Chart.yaml
- src/mail/package.json
- ✨(backend) add soft delete and restore API endpoints to documents #516
- ✨(backend) allow organizing documents in a tree structure #516
- ✨(backend) add "excerpt" field to document list serializer #516
- ✨(backend) add github actions to manage Crowdin workflow #559 & #563
- 📈Integrate Posthog #540
- 🏷️(backend) add content-type to uploaded files #552
- ✨(frontend) export pdf docx front side #537
- 💄(frontend) add abilities on doc row #581
- 💄(frontend) improve DocsGridItem responsive padding  #582
- 🔧(backend) Bump maximum page size to 200 #516
- 📝(doc) Improve Read me #558
- 🐛Fix invitations #575
- 🔥(backend) remove "content" field from list serializer #516
---
**Full Changelog:** https://github.com/numerique-gouv/impress/compare/v2.0.1...v2.1.0
> 🔖(minor) release 2.1.0

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
- SECURITY.md
We need a safe way for people to report vulnerabilities.
And guidelines for conduct. 
People now can go on SECURITY.md and follow our policy.
And our of code of conduct.
> 📝(doc) Add security.md and codeofconduct.md

- src/helm/impress/Chart.yaml
- src/helm/impress/README.md
- src/helm/impress/generate-readme.sh
- src/helm/impress/templates/backend_deployment.yaml
- src/helm/impress/templates/frontend_deployment.yaml
- src/helm/impress/templates/yprovider_deployment.yaml
- src/helm/impress/values.yaml
In order to avoid a service interruption during a Kubernetes (k8s) upgrade, we add a Pod Disruption Budget (PDB) to deployments.
> ✨(helm) add pdbs to deployments

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-export.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteSuggestionMenu.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/useHeadings.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/stores/useEditorStore.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/stores/useHeadingStore.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/styles.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/types.tsx
- src/frontend/apps/impress/src/features/docs/doc-table-content/components/Heading.tsx
Recent upgrade of Blocknote.js add the export `PageBreak` block. 
This PR add this feature to our editor.
[scrnli_XXGTCdUYLylzAi.webm](https://github.com/user-attachments/assets/9b60d5a1-efa5-4e1a-b5c7-4611530bba39)
> ✨(frontend) Add export page break

- .github/workflows/impress-frontend.yml
- Makefile
- README.md
- docker-compose.yml
- docker/files/etc/nginx/conf.d/default.conf
Nginx is used to proxify keycloak in our development configuration. When
a new user is created keycloak is send a large amount of headers in its
response and the default nginx config is not enough to handle this
amount of headers. We have to increase the proxy buffer size to handle
them.
We all remove the usage of dockerize in this PR to use healthcheck in docker compose services.
And then change all make run commands. The run command is starting everything. The run-back
command is starting all services needed to use the backend application
and then the run-frontend starts only the frontend-dev service.
> increase nginx buffer size when proxifying keycloak 

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-versioning/components/ModalSelectVersion.tsx
When you are a reader member, you have the right to see the version but you cannot restore them. 
So, we hide the restore button when you are a reader.
> 🛂(frontend) Restore version visibility

- src/frontend/apps/impress/src/features/docs/doc-header/components/ModalExport.tsx
The rendered text had unwanted line breaks in middle of them. It was because we were not using the appropriate Text component, the one to be used in the one from react-pdf.
> 🐛(front) improve text rendering in pdf

- CHANGELOG.md
- src/frontend/apps/impress/package.json
- src/frontend/apps/impress/src/features/docs/doc-header/components/ModalExport.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/blocks/Table.tsx
- src/frontend/apps/impress/src/types/@ag-media/react-pdf-table.d.ts
- src/frontend/yarn.lock
The previous way of rendering table was causing issues when tables could not fit on one page. I then came accross this discussion https://github.com/diegomura/react-pdf/issues/2343. The author created a lib to improve the rendering of table, it's better, but still not perfect maybe.
> Improving PDF is quite cumbersome, so I encourage you to test on your side to see if the rendering is correct. Otherwise we'll need to put more effort into this by going deep in the implementation, not sure we want to put that much of energy in it. Let's try this lib before :)
> ♻️(front) improve table pdf rendering

- src/frontend/apps/e2e/__tests__/app-impress/auth.setup.ts
- src/frontend/apps/e2e/playwright.config.ts
An error occures sometimes blocking all the tests. This commit fix the issue by waiting for the
authentication to finish before navigating to the next page.
See: https://github.com/suitenumerique/docs/actions/runs/13159675493/job/36724973820?pr=613
Wait for the auth url before passing the the next steps.
> ✅(e2e) fix error authenticate navigation to finish

- bin/_config.sh
- docker-compose.yml
The helper bin/compose was using the option -p to set the compose project name but this option is not used in the Makefile. This can lead to different way to use the docker compose file definition with different project name. In order to have a consistent name everywhere and for everybody, we set the name in the docker compose file itself.
> ♻️(compose) set compose name in the docker-compose file

- CHANGELOG.md
- src/backend/core/api/viewsets.py
- src/backend/core/tests/documents/test_api_documents_media_auth.py
A user reported that mp4 video were not working. 
The request to download the video is getting a 403 whereas images work on the same document :thinking: 
The regex to validate media file extensions was too restrictive. Make it more permissive to allow any type of file extensions.
> 🐛(backend) allow more extensions for media download

- src/backend/core/models.py
In the restore method, all the ancestors with a deleted_at date set are extracted from the database and then the oldest value is extracted using the min python function. This usage of min can be removed by sorting directly the deleted_at at the database level and then fetching the first one. It's faster and easier to maintain.
> ♻️(back) extract ancestor deleted_at directly from db in restore method

- CHANGELOG.md
- src/backend/impress/settings.py
- src/frontend/apps/impress/src/stores/useSentryStore.tsx
- src/frontend/servers/y-provider/src/services/sentry.ts
To ease filtering issues on sentry, we want to use tags instead of extra scope. Tags are indexed and searchable, it's not the case with extra scope. Moreover using setExtra to add additional data is deprecated.
> ♻️(front) use sentry tags instead of extra scope

- CHANGELOG.md
- src/backend/core/api/__init__.py
- src/backend/core/api/viewsets.py
- src/backend/core/tests/documents/test_api_document_invitations.py
- src/backend/core/tests/documents/test_api_documents_favorite_list.py
favorite_list endpoint is accessible to anonymous user. This lead to an
error 500. This endpoint should be accessible only to authenticated
users.
> 🔒️(back) restrict access to favorite_list endpoint

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-table-content/components/TableContent.tsx
During a useEffect cleaning, the selector was not the correct one. The debounce was not being removed correctly neither.
> 🐛(frontend) remove scroll listener table content

- src/backend/impress/settings.py
We want to persist the session during development. Otherwise the session is reset everytime the server is restart. This behavior make developing both a front and back feature a nigthmare, we spend our time login again and again
> ⚡️(back) use redis as session backend in developement

- CHANGELOG.md
- src/backend/core/services/ai_services.py
- src/backend/core/tests/documents/test_api_documents_ai_transform.py
- src/backend/core/tests/documents/test_api_documents_ai_translate.py
- src/backend/core/tests/test_services_ai_services.py
- src/frontend/apps/impress/src/features/docs/doc-editor/api/useDocAITransform.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteToolBar/AIButton.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/custom-blocks/QuoteBlock.tsx
To translate with the AI we are using lossy functions `blocksToMarkdownLossy` / `tryParseMarkdownToBlocks`, it transforms the content editor to markdown. The problem is this transpilation is very lossy, we loose color, background, table size, line break etc...
We will use html instead of markdown to do the translation, html can carry much more information that markdown about the content style.
[scrnli_Ug6vr23om8ZN8E.webm](https://github.com/user-attachments/assets/949c760b-68fa-4f4e-acf3-a8e7f7f3a00b)
[scrnli_aTe1Ed2p695SF2.webm](https://github.com/user-attachments/assets/2b020e0f-4d5f-472b-a630-d292d03f535d)
[scrnli_v7YQ56N18Q3O5n.webm](https://github.com/user-attachments/assets/81f00dbc-d60d-4d3e-9941-66b33ff45a5d)
> ⚡️Improve AI translations formatting

- CHANGELOG.md
- src/frontend/apps/impress/jest.config.ts
- src/frontend/apps/impress/src/core/config/ConfigProvider.tsx
- src/frontend/apps/impress/src/features/auth/hooks/__tests__/useAuth.test.tsx
- src/frontend/apps/impress/src/features/auth/hooks/useAuth.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/__tests__/DocToolBox.spec.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/language/index.ts
- src/frontend/apps/impress/src/libs/Analytics.tsx
- src/frontend/apps/impress/src/libs/index.ts
- src/frontend/apps/impress/src/services/PosthogAnalytic.tsx
- src/frontend/apps/impress/src/services/index.ts
Add abstract classes for analytics services.
We will be able to add easily any analytic services.
Our first analytic service use case is Posthog.
https://github.com/suitenumerique/docs/blob/09cd10222b4992789a9a159b9bfb5e3f6d650171/src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx#L91-L98
> 📈(frontend) abstract analytics classes

- README.md
The mention of min.io's licence in the README is confusing.
We are only using min.io for development purposes and this has nothing to do with the project's licence.
Remove mention to min.io's AGPL licence.
> 📝(README) remove mention to min.io's AGPL licence

- .github/workflows/helmfile-linter.yaml
- CHANGELOG.md
- src/helm/helmfile.yaml
Latest release of helmfile is applying the change related before as a warning. Environnements must be before releases but not in the same document of repositories.
> 🚨(helm) fix helmfile lint

- src/backend/core/tests/swagger/test_openapi_schema.py
- src/backend/impress/urls.py
Swaggers urls where not using the same base route path /api/v1.0, we prepend it to have the same path everywhere. Moreover, a double slash was used for swagger and redoc dashboard.
> ♻️(back) use same base route path for swagger

- README.md
The current link redirects to a 404. New link redirect to homepage.
> 🐛(readme) fix preprod link to redirect to homepage

- CHANGELOG.md
- CONTRIBUTING.md
- gitlint/gitlint_emoji.py
Many developers use uppercase as the first letter in their commit messages, it creates an error.
We will allow uppercase in commit messages to lower frustration when committing.
> 🚨(gitlint) Allow uppercase in commit messages

- CHANGELOG.md
- README.md
Just like docker-compose, create a link to GNU Make's site on its first mention.
More standard documentation.
Add a link for GNU Make's webpage when it's first mentioned
> 📝(README) Added GNU Make link to README

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-routing.spec.ts
- src/frontend/apps/impress/src/core/AppProvider.tsx
- src/frontend/apps/impress/src/libs/Analytics.tsx
- Users could still be able to edit a document if the session was expired. It could give the feeling that the document was not saved.
- `useAnalytics` was unmounting children because of function not correctly dispatched.
If during a mutation request (POST, PUT, DELETE), the server returns a 401 error, the user is redirected to the 401 page.
> 🚚(frontend) redirect to 401 page when 401 error

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/package.json
- src/frontend/apps/impress/src/features/docs/doc-export/blocks-mapping/imageDocx.tsx
- src/frontend/apps/impress/src/features/docs/doc-export/blocks-mapping/imagePDF.tsx
- src/frontend/apps/impress/src/features/docs/doc-export/utils.ts
- src/frontend/package.json
- src/frontend/packages/eslint-config-impress/package.json
- src/frontend/packages/i18n/package.json
- src/frontend/servers/y-provider/package.json
- src/helm/helmfile.yaml
- src/helm/impress/Chart.yaml
- src/mail/package.json
- 📝(doc) Added GNU Make link to README #750
- ✨(frontend) add pinning on doc detail #711
- 🚩(frontend) feature flag analytic on copy as html #649
- ✨(frontend) Custom block divider with export #698
- 🌐(i18n) activate dutch language #742
- ✨(frontend) add Beautify action to AI transform #662
- ✨(frontend) add Emojify action to AI transform #662
- 🧑‍💻(frontend) change literal section open source #702
- ♻️(frontend) replace cors proxy for export #695
- 🚨(gitlint) Allow uppercase in commit messages #756
- ♻️(frontend) Improve AI translations #662
- 🐛(frontend) SVG export #706
- 🐛(frontend) remove scroll listener table content  #688
- 🔒️(back) restrict access to favorite_list endpoint #690
- 🐛(backend) refactor to fix filtering on children 
and descendants views #695
- 🐛(action) fix …
> 🔖(minor) release 2.5.0

- CHANGELOG.md
- publiccode.yml
publiccode.yml is a standard for describing Free Software projects, similar to other initiatives such as https://codemeta.github.io.
It is particularly suitable for describing projects funded by public administrations. See https://github.com/publiccodeyml/publiccode.yml
> 📝(doc) add publiccode.yml

- CHANGELOG.md
- src/backend/core/api/viewsets.py
- src/backend/core/tests/documents/test_api_documents_cors_proxy.py
The cors-proxy endpoint allowed to use every type of files and to execute it in the browser. We limit the scope only to images and Content-Security-Policy and Content-Disposition headers are also added to not allow script execution that can be present in a SVG file.
> 🐛(back) allow only images to be used with the cors-proxy

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-search.spec.ts
- src/frontend/apps/impress/src/hook/useCmdK.tsx
ctrl+k interaction is as well used in the editor. 
If the user has a focus on the editor, we don't open the searchmodal.
> 🚸(frontend) ctrl+k modal not when editor is focused

- src/backend/core/api/viewsets.py
- src/backend/core/models.py
I'm starting to test Docs deployment on various cloud providers. I will send follow-up PRs soon for a few more of them.
Some providers with S3-compatible APIs have slightly different implementations. In this case, Scaleway didn't accept version_id="" and has a different version ID scheme. This was tested successfully and should remain compatible with any other provider.
> 🐛(storage) fix compatibility with Scaleway Object Storage

- CHANGELOG.md
- CONTRIBUTING.md
Fix https://github.com/suitenumerique/docs/issues/734
(Redo https://github.com/suitenumerique/docs/pull/744)
> 📄(legal) Require contributors to sign a DCO

- bin/Tiltfile
The Tilt stack was not starting properly due to dependency issues. We need to wait for PostgreSQL to be running before starting the migration.
> 🐛(ci) fix Tilt resources dependencies

- CHANGELOG.md
- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/models.py
- src/backend/core/tests/documents/test_api_document_accesses.py
- src/backend/core/tests/test_models_document_accesses.py
Every user having an access to a document, no matter its role have access to the entire accesses list with all the user details. Only owner or admin should be able to have the entire list, for the other roles, they have access to the list containing only owner and administrator with less information on the username. The email and its id is removed
> 🔒️(back) restrict accesss to document accesses

- CHANGELOG.md
- UPGRADE.md
- src/backend/pyproject.toml
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/package.json
- src/frontend/apps/impress/src/features/docs/doc-export/components/ModalExport.tsx
- src/frontend/apps/impress/src/features/service-worker/__tests__/useSWRegister.test.tsx
- src/frontend/apps/impress/src/features/service-worker/hooks/useSWRegister.tsx
- src/frontend/apps/impress/src/features/service-worker/service-worker.ts
- src/frontend/package.json
- src/frontend/packages/eslint-config-impress/package.json
- src/frontend/packages/i18n/package.json
- src/frontend/servers/y-provider/package.json
- src/helm/env.d/dev/values.impress.yaml.gotmpl
- src/helm/helmfile.yaml
- src/helm/impress/Chart.yaml
- src/mail/package.json
- 📄(legal) Require contributors to sign a DCO #779
- ♻️(frontend) Integrate UI kit #783
- 🏗️(y-provider) manage auth in y-provider app #804
- 🐛(backend) compute ancestor_links in get_abilities if needed #725
- 🔒️(back) restrict access to document accesses #801
> 🔖(major) release 3.0.0

- CHANGELOG.md
- src/backend/core/api/serializers.py
- src/backend/core/tests/documents/test_api_documents_update.py
We recently extract images url in the content. For this, we assume that the document content is always in base64. We enforce this assumptim by checking if it's a valide base64 in the serializer.
> 🐛(back) validate document content in serializer

- CHANGELOG.md
- env.d/development/common.dist
- src/backend/core/api/viewsets.py
- src/backend/core/tests/test_api_config.py
- src/backend/impress/settings.py
- src/frontend/apps/e2e/__tests__/app-impress/config.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
- src/frontend/apps/impress/src/core/config/api/useConfig.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteToolBar/BlockNoteToolbar.tsx
Added a feature flag check to ensure the AIGroupButton is only rendered when AI_FEATURE_ENABLED is explicitly set to "true". This prevents the AI button from appearing when the feature is not configured or disabled.
Fixes #782
> 🐛(frontend) conditionally render AI button in toolbar

- CHANGELOG.md
- src/frontend/apps/impress/jest.config.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/__tests__/useSaveDoc.test.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/useSaveDoc.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/stores/useHeadingStore.tsx
- src/frontend/apps/impress/src/features/docs/doc-search/components/DocSearchModal.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LefPanelTargetFilters.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanel.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelHeader.tsx
Fixes after investigate about potential performance issues.
> ⚡️Fixes small perf issues

- CHANGELOG.md
- env.d/development/common.dist
- src/backend/core/api/viewsets.py
- src/backend/core/services/config_services.py
- src/backend/core/tests/conftest.py
- src/backend/core/tests/documents/test_api_documents_ai_transform.py
- src/backend/core/tests/documents/test_api_documents_ai_translate.py
- src/backend/core/tests/test_api_config.py
- src/backend/core/tests/test_api_footer.py
- src/backend/core/tests/test_api_utils_ai_document_rate_throttles.py
- src/backend/core/tests/test_api_utils_ai_user_rate_throttles.py
- src/backend/core/urls.py
- src/backend/impress/settings.py
- src/frontend/apps/e2e/__tests__/app-impress/config.spec.ts
- src/frontend/apps/impress/public/contents/footer-demo.json
- src/frontend/apps/impress/public/contents/footer-dsfr.json
- src/helm/env.d/dev/values.impress.yaml.gotmpl
- We want to have different footer content per environment.
- We want to be able to not have footer as well
- We added `FRONTEND_FOOTER_FEATURE_ENABLED` environment variable, a feature flag to enable or not the footer.
- We added the `FRONTEND_URL_JSON_FOOTER` environment variable. It will give the possibility to generate your own footer content in the frontend.
https://github.com/suitenumerique/docs/blob/1972ef4d07eb2be2b7b0ac901b00ac8ffc8b9d7f/src/frontend/apps/impress/public/contents/footer-demo.json
> 🔧(backend) configurable footer

- README.md
Having a preprod account using a yopmail account was a security bad practice
> 📝(readme) remove preprod account from readme

- CHANGELOG.md
- src/backend/core/api/filters.py
- src/backend/core/migrations/0021_activate_unaccent_extension.py
- src/backend/core/tests/documents/test_api_documents_descendants_filters.py
We want the document search on title to be accent-insensitive.
This should work in both cases:
- search for "vélo" when the document title contains "velo"
- search for "velo" when the document title contains "vélo"
> 🚸(backend) make document search on title accent-insensitive

- CHANGELOG.md
- src/frontend/apps/impress/src/core/config/api/useConfig.tsx
- src/frontend/apps/impress/src/features/language/hooks/useLanguageSynchronizer.ts
We will serve the config from the cache if available in waiting for the config to be loaded.
It will remove the loading time for the config except when the config is not available in the cache.
> ⚡️(frontend) reduce unblocking time for config

- README.md
Info message so people fulfill their licencing obligations
> 📝(readme) update xl packages info

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteToolBar/FileDownloadButton.tsx
- src/frontend/apps/impress/src/utils/__tests__/url.test.tsx
- src/frontend/apps/impress/src/utils/url.ts
Added a safety check for URLs in the FileDownloadButton component. Now, before opening a URL, it verifies if the URL is safe using the isSafeUrl function.
This prevents potentially unsafe URLs from being opened in a new tab.
> 🔒(frontend) enhance file download security

- CHANGELOG.md
- src/backend/impress/settings.py
Deployments that don't rely on Docker should be given the option to use a different data directory.
Allow customization of the `DATA_DIR` through an environment variable of the same name.
If the environment variable is not set the behaviour remains the same as before.
> 🔧(backend) Allow overwriting the data directory

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-routing.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/language.spec.ts
- src/frontend/apps/impress/conf/default.conf
- src/helm/env.d/dev/values.impress.yaml.gotmpl
- src/helm/helmfile.yaml
We improve the nginx way to access to a specific doc, to not have a 404 before accessing the resource.
We stop to wait for a initial attempt that give a 404. 
If we see a UUID in the url we will redirect to the doc/[id] page. 
`Next` will then manage the 404.
- go to `src/frontend/apps/impress`
- `yarn build`
- Access the app from nginx, in `docker-compose.yml`, add this service:
```yaml
nginx-ci:
image: nginx:1.25
ports:
- "3000:3000"
volumes:
- ./src/frontend/apps/impress/conf/default.conf:/etc/nginx/conf.d/default.conf
- ./src/frontend/apps/impress/out:/usr/share/nginx/html
depends_on:
- app-dev
- keycloak
```
- go to `http://localhost:3000`
> 🐛(nginx) fix 404 when accessing a doc

- CHANGELOG.md
- src/backend/impress/settings.py
The `BrowsableAPIRenderer` generates a form to test POST/PUT/... actions and fill the FK fields with unfiltered data. This issue has been spoted on visio and fixed suitenumerique/meet#508
> 🔒️(drf) disable browsable HTML API renderer

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-export.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-member-list.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-management/hooks/useTrans.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocRoleDropdown.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareMemberItem.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModal.tsx
Some actions were not available in the frontend but allowed in the backend.
We bind the UI with the ability access coming from the backend.
> ♻️(frontend) bind ui with ability access

- docs/env.md
📝(doc) added AI_FEATURE_ENABLED
This is false by default. Without this env setting on true AI will not be available in the docs application. The setting was missing in the env options.
Complete documentation
> 📝(doc)  Update env.md add AI_FEATURE_ENABLED

- CHANGELOG.md
- renovate.json
- src/backend/pyproject.toml
- src/frontend/apps/e2e/package.json
- src/frontend/apps/impress/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-impress/package.json
- src/frontend/packages/i18n/package.json
- src/frontend/servers/y-provider/package.json
- src/frontend/yarn.lock
- src/helm/helmfile.yaml
- src/helm/impress/Chart.yaml
- src/mail/package.json
- 🐛(frontend) fix list copy paste #943
> 🔖(patch) release 3.2.1

- CHANGELOG.md
- src/frontend/apps/impress/next.config.js
- src/frontend/apps/impress/src/api/APIError.ts
- src/frontend/apps/impress/src/api/__tests__/APIError.test.ts
- src/frontend/apps/impress/src/api/__tests__/config.test.ts
- src/frontend/apps/impress/src/api/__tests__/fetchApi.test.tsx
- src/frontend/apps/impress/src/api/__tests__/helpers.test.tsx
- src/frontend/apps/impress/src/api/__tests__/utils.test.ts
- src/frontend/apps/impress/src/api/config.ts
- src/frontend/apps/impress/src/api/fetchApi.ts
- src/frontend/apps/impress/src/api/helpers.tsx
- src/frontend/apps/impress/src/api/types.ts
- src/frontend/apps/impress/src/api/utils.ts
- src/frontend/apps/impress/src/core/AppProvider.tsx
- src/frontend/apps/impress/src/core/config/api/useConfig.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/useSaveDoc.tsx
- src/frontend/apps/impress/src/features/docs/doc-export/utils.ts
- src/frontend/apps/impress/src/features/service-worker/service-worker.ts
- src/frontend/apps/impress/src/services/PosthogAnalytic.tsx
- src/frontend/apps/impress/src/utils/url.ts
- src/frontend/packages/eslint-config-impress/common.js
- src/frontend/servers/y-provider/.eslintrc.cjs
- src/frontend/servers/y-provider/jest.config.js
- src/frontend/servers/y-provider/src/servers/appServer.ts
- Simplify if statement 
- Simplify redundant conditional expression
- Remove unnecessary local variable
- Remove var usage instead of let/const
- Add explicit React import to ensure JSX compatibility
- Add test file to improve coverage
- Add documentation
> ♻️ (frontend) do multiple refacto

- CHANGELOG.md
- docs/env.md
- src/backend/core/api/viewsets.py
- src/backend/core/enums.py
- src/backend/core/malware_detection.py
- src/backend/core/tests/documents/test_api_documents_attachment_upload.py
- src/backend/core/tests/documents/test_api_documents_media_auth.py
- src/backend/core/tests/test_malware_detection.py
- src/backend/impress/__init__.py
- src/backend/impress/celery_app.py
- src/backend/impress/settings.py
- src/backend/pyproject.toml
The django lasuite library has a dedicated module managing malware detection.
We have to configure it using django settings and then put the logic we want to apply in a callback.
While the analyse is not made, we set a temporary status to the file metadata and this status is check in the media-auth endpoint to determine is the s3 signature should be return or not.
If a file is glas as unsafe, it is deleted.
> django-lasuite malware detection integration

- .github/workflows/impress.yml
- CHANGELOG.md
- SECURITY.md
- docs/env.md
- docs/examples/impress.values.yaml
- docs/installation.md
- src/backend/core/api/viewsets.py
- src/backend/core/services/ai_services.py
- src/backend/core/services/collaboration_services.py
- src/backend/core/tests/documents/test_api_document_invitations.py
- src/backend/core/tests/documents/test_api_documents_ai_transform.py
- src/backend/core/tests/documents/test_api_documents_ai_translate.py
- src/backend/core/tests/documents/test_api_documents_attachment_upload.py
- src/backend/core/tests/documents/test_api_documents_create_for_owner.py
- src/backend/core/tests/documents/test_api_documents_move.py
- src/backend/core/tests/documents/test_api_documents_update_extract_attachments.py
- src/frontend/apps/e2e/__tests__/app-impress/doc-export.spec.ts
- src/frontend/apps/impress/src/components/Text.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/hook/useSaveDoc.tsx
- src/frontend/apps/impress/src/features/docs/doc-export/blocks-mapping/tablePDF.tsx
- src/frontend/apps/impress/src/features/service-worker/service-worker.ts
- src/helm/env.d/dev/values.impress.yaml.gotmpl
- src/helm/impress/templates/_helpers.tpl
We get lot of pull requests about typo.
We add [codespell](https://github.com/codespell-project/codespell) linter in the CI, it will inform us if we introduce spell mistakes.
This linter checks all the project.
> 🩺(CI) add lint spell mistakes

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/common.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/DocEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/AlertNetwork.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/AlertPublic.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocHeader.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/hooks/index.ts
- src/frontend/apps/impress/src/features/docs/doc-management/hooks/useIsCollaborativeEditable.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/stores/useProviderStore.tsx
- src/frontend/apps/impress/src/features/service-worker/__tests__/ApiPlugin.test.tsx
- src/frontend/apps/impress/src/features/service-worker/__tests__/OfflinePlugin.test.tsx
- src/frontend/apps/impress/src/features/service-worker/__tests__/useOffline.test.tsx
- src/frontend/apps/impress/src/features/service-worker/__tests__/useSWRegister.test.tsx
- src/frontend/apps/impress/src/features/service-worker/conf.ts
- src/frontend/apps/impress/src/features/service-worker/hooks/useOffline.tsx
- src/frontend/apps/impress/src/features/service-worker/hooks/useSWRegister.tsx
- src/frontend/apps/impress/src/features/service-worker/index.ts
- src/frontend/apps/impress/src/features/service-worker/plugins/ApiPlugin.ts
- src/frontend/apps/impress/src/features/service-worker/plugins/OfflinePlugin.ts
- src/frontend/apps/impress/src/features/service-worker/service-worker-api.ts
- src/frontend/apps/impress/src/features/service-worker/service-worker.ts
- src/frontend/apps/impress/src/pages/_app.tsx
- src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
We can have none connected users who overwrite documents with connected users.
See: https://github.com/suitenumerique/docs/issues/486
If an editor is working on a **shared** document but is not connected to the collaborative server
we are now blocking the edition. 
We are blocking when:
- The user is online (has internet)
- The user is not connected to the collaboration server
- The doc has members or is "public editable" or "auth editable"
---
In the demo we are not connected to the collaboration server.
[scrnli_pkFb1Rn1YN1lhY.webm](https://github.com/user-attachments/assets/67f6e280-a6c0-46a7-ac3f-77099da7a255)
> 🛂(frontend) block edition to not connected users

- CHANGELOG.md
- docs/env.md
- src/backend/impress/settings.py
We want to be able to increase the duration of the cookie session.
Add django-configuration IntegerValue to expose the `SESSION_COOKIE_AGE` as an environment variable.
> ✨(backend) allow setting session cookie age via env var

- src/helm/env.d/dev/values.impress.yaml.gotmpl
Fix certificate directory reference that still pointed to Python 3.12 folder after upgrading to Python 3.13. Resolves certificate verification errors in tilt stack caused by incorrect certificate location.
> 🐛(tilt) update certificate path for Python 3.13 upgrade

- CHANGELOG.md
- src/frontend/servers/y-provider/__tests__/server.test.ts
- src/frontend/servers/y-provider/src/servers/appServer.ts
Problem:
- Default Express JSON parser limit (100kb) is insufficient for larger transcription files
- 2-hour audio transcriptions slightly exceed the 100kb limit, causing request failures
Solution:
- Implemented custom middleware to apply different JSON parser configurations based on route
- Applied 500kb limit specifically for transcription conversion endpoints
- Maintained default limits for all other routes to preserve security
Technical notes:
- Could not find a built-in Express solution to specify parser config per route
- Custom middleware conditionally applies the appropriate parser configuration
> fix document converter with large transcript

- src/frontend/Dockerfile
Cyberwatch reported security issues with the frontend Docker image.
> 🔒️(front) improve docker image security

- README.md
> 📝(doc) fix path to env doc on readme

- docker-compose.yml
We node service in docker compose can be a helper to use node locally without installing it. Docs requires at least node 22 so we upgrade it to node 22.
> ⬆️(compose) upgrade node image to version 22

- CHANGELOG.md
- src/frontend/servers/y-provider/Dockerfile
We want to build the yjs Docker image with the latest minor version in order to avoid outdated images.
Stop pinning node to minor version on yjs docker image
> 📌(yjs) stop pinning node to minor version on yjs docker image

- docs/examples/impress.values.yaml
Remove the `auth-url` annotation and add the
`COLLABORATION_BACKEND_BASE_URL` variable, introduced in 3.0.0.
Mount the development CA to the yProvider container to allow TLS connections with the backend.
The helm charts are outdated as of release 3.0.0. This adds the correct variables and certificates for yProvider when deploying to the example kind cluster.
> :memo:(self-hosted) update collaboration vars

- env.d/development/common.dist
- env.d/development/common.e2e.dist
In local development the notification to the yprovider server was not working anymore because of a recent change in the container name.
We adapt the env variables to match the new container name.
> 🐛(env) update yprovider env for local development

- Makefile
> fix: Makefile failing on run-frontend-development

- src/backend/impress/settings.py
The db engine postgresql_psycopg2 does not exists anymore in django but for BC compat it is possible to use it in the configuration and it is replace by postgresql at runtime. We changed this settings to use the good one.
> 🔧(back) remove usage of deprecated db engine

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/footer.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/home.spec.ts
- src/frontend/apps/impress/cunningham.ts
- src/frontend/apps/impress/src/cunningham/cunningham-tokens.css
- src/frontend/apps/impress/src/cunningham/cunningham-tokens.ts
- src/frontend/apps/impress/src/features/header/components/Title.tsx
Docs got homologated, so we can remove the beta logo from the DSFR theme.
> 🔥(frontend) remove Beta from logo

- CHANGELOG.md
- src/backend/impress/settings.py
- src/frontend/servers/y-provider/src/env.ts
Related to https://github.com/suitenumerique/docs/issues/909
> ✨(backend) support `_FILE` environment variables for secrets

- src/backend/core/api/serializers.py
- src/backend/core/services/converter_services.py
- src/backend/core/tests/documents/test_api_documents_create_for_owner.py
- src/backend/core/tests/test_services_converter_services.py
Renamed the `convert_markdown` method to `convert` to prepare for an all-purpose conversion endpoint, enabling support for multiple formats and simplifying future extension.
Renamed the `convert_markdown` method to `convert` to prepare for an all-purpose conversion endpoint, enabling support for multiple formats and simplifying future extension.
> ♻️(backend) rename `convert_markdown` to `convert`

- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridActions.tsx
- src/frontend/apps/impress/src/features/home/components/HomeContent.tsx
Multipage is available now, so we remove the "Available soon" tag from the home page.
> 🔥Available soon

- CHANGELOG.md
- Dockerfile
Using the `apk` commands with the `--no-cache` parameter for package installation and upgrade will prevent the package index from being cached and reduce the built image size.
- Add `--no-cache` with all the `apk upgrade` and `apk add` commands
- Remove additional `apk update` command
> Optimize Dockerfile to use `apk` with `--no-cache`

- CHANGELOG.md
- src/helm/impress/templates/ingress_collaboration_api.yaml
- src/helm/impress/templates/ingress_collaboration_ws.yaml
Closes #890
Remove the service blocks outside the conditionals in the collaboration API and WS templates. This makes these blocks follow the same pattern uses in other places in these templates and in other templates in the repo.
> 🐛(helm) charts generate invalid YAML for collaboration API / WS

- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridItem.tsx
It was decided to add a visibility icon near the title of the document in the grid view.
> 💄(frontend) visibility icon near title

- CHANGELOG.md
- src/frontend/apps/impress/src/cunningham/cunningham-style.css
At the bottom of the tree panel, the subdocs were not clickable due to a CSS issue.
This commit adjusts the CSS to ensure that the subdocs can be unfolded properly.
https://github.com/user-attachments/assets/e265b983-eada-4938-ab1e-d3eea351c4a0
> 🐛(frontend) fix unfold subdocs not clickable at the bottom

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-header/__tests__/DocToolBox.spec.tsx
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/api/useDuplicateDoc.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocTreeItemActions.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridActions.tsx
When we duplicate a document from a document page, we now redirect the user to the newly created document.
We added a Duplicate button to the document tree options as well.
> ♻️(frontend) Duplicate

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocTitle.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/api/useDoc.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocRoleDropdown.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareAddMemberList.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareInvitation.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareMember.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/api/useDocTree.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocSubPageItem.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocTree.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocTreeItemActions.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/index.ts
- src/frontend/apps/impress/src/features/docs/doc-tree/index.ts
- src/frontend/apps/impress/src/features/docs/doc-tree/utils.ts
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelDocContent.tsx
Improve tree stability by limiting the requests. 
We now only load the tree request one time then we let the `treeContext` handle the state without mutating it directly.
We do not do the doc subpage request anymore, the `treeContext` seems to have already the data we need, we just need to update the tree node when needed.
> ⚡️(frontend) improve tree stability

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-routing.spec.ts
- src/frontend/apps/impress/src/core/AppProvider.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/api/useUpdateDoc.tsx
To capture a 401 we were using `onError` in the queryClient default mutation options. 
The problem is this way does not capture globally the `onError`, if a mutation uses as well is own `onError`, it will override the default one, causing the 401 to not be captured anymore.
We now use [MutationCache](https://tanstack.com/query/latest/docs/reference/MutationCache), which allows us to capture globally the `onError`, even if a mutation has its own `onError` defined, this global one will still be called.
> 🐛(frontend) 401 redirection overridden

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-inherited-share.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-management/api/useUpdateDocLink.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocDesynchronized.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModal.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModalFooter.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocVisibility.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocTree.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocTreeItemActions.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/hooks/useTreeUtils.tsx
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridItem.tsx
The subdocs can now have their own link reach properties, dissociated from the parent document.
[Test 8989 - Docs.webm](https://github.com/user-attachments/assets/94c6b3dc-2dca-4318-bcbb-8b52b91a7684)
> ✨(frontend) subdocs can manage link reach

- CHANGELOG.md
- docs/env.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-export.spec.ts
- src/frontend/apps/impress/package.json
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteEditor.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteSuggestionMenu.tsx
- src/frontend/apps/impress/src/features/docs/doc-editor/components/xl-multi-column/index.ts
We add multi columns support for editor, now you can add columns to your document.
Works with export.
📄AGPL feature.
https://github.com/user-attachments/assets/9eebd8b8-629c-4f0a-a8f8-54e08a61a977
> ✨(frontend) add multi columns support for editor

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-editor/styles.tsx
Improve text accessibility by enhancing the contrast of links on colored backgrounds.
- Changed link color from greyscale-500 to greyscale-600 to make it easier to read on colored backgrounds as suggested in the issue
.
- Tried to fix the case where text color === background color (like red on red) using CSS overrides.
- But it didn’t work, because BlockNote.js uses inline styles that are too strong to override.
- We may need to fix this directly inside BlockNote.js to allow better control of contrast for colored texts.l
> ♿(frontend) improve contrast for links

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-search.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-search/components/DocSearchSubPageContent.tsx
The root parent was not included in the search.
When searching for documents, the root parent document is now included in the search results if it matches the search query.
> 🐛(frontend) include root parent in search

- docs/examples/helm/impress.values.yaml
- docs/installation/kubernetes.md
- src/helm/env.d/dev/values.impress.yaml.gotmpl
Yesterday during a deployment, we discovered that these variables are unused:
POSTGRES_DB
POSTGRES_USER
POSTGRES_PASSWORD
> ♻️(documentation) remove unused environment variables

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/language.spec.ts
- src/frontend/apps/impress/src/i18n/config.ts
- src/frontend/apps/impress/src/i18n/initI18n.ts
- src/frontend/apps/impress/src/pages/_document.tsx
Add a new HtmlLangUpdater component to dynamically update the <html lang> attribute based on the current locale from i18next. This improves accessibility.
issue : [875](https://github.com/suitenumerique/docs/issues/875)
https://github.com/user-attachments/assets/ba8d01d9-c3c6-4c94-bd9e-b01892558fd1
> 🌐(frontend) set html lang attribute dynamically based on current loc

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-export.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/language.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/utils-common.ts
- src/frontend/apps/impress/src/features/docs/doc-export/components/ModalExport.tsx
This PR improves the accessibility of exported PDF documents by explicitly setting the document language to fr-FR as suggested in the issue [1133](https://github.com/suitenumerique/docs/issues/1133)
This ensures proper pronunciation by screen readers (e.g. VoiceOver, NVDA), especially for homographs like “mobile” that differ between French and English.
> ♿(frontend) inject language attribute to pdf export

- docs/installation/compose.md
Corrected the commands in step 1
> 📝(doc) Fix commands in docker compose section

- CHANGELOG.md
- Makefile
- bin/_config.sh
- docs/troubleshoot.md
The project has some compatibilities issues with Windows.
> 🐛 Fix some windows compatibilities

- .github/workflows/crowdin_upload.yml
- .github/workflows/impress.yml
The setup-python action is able to cache the dependencies and reuse this cache while the pyproject file has not changed. It is easy to setup, just the package manager used has to be declared in the cache settings.
> ⚡️(ci) use setup-python cache option

- CHANGELOG.md
- src/backend/core/api/serializers.py
- src/backend/core/tests/serializers/test_user_light_serializer.py
In the UserlightSerializer, if the user has no short_name or full_name, we have no info about the user. We decided to use the email identifier and slugify it to have a little bit information.
Fix #1210
> ♻️(backend) fallback to email identifier when no name

- src/mail/bin/html-to-plain-text
- src/mail/bin/mjml-to-html
That allows downstream packages to e.g. split the builds of frontend/backend/mail, as it's the case in nixpkgs: https://github.com/NixOS/nixpkgs/commit/5597a4f8f9f82e6a4829f3527728016c07838f4f
> mail: make DIR_MAILS variable changeable

- .github/workflows/impress-frontend.yml
We don't need to run the bundle-size-check job if the app didn't change.
Only if the `yarn.lock` file or the app have changed, the bundle-size-check job will be triggered.
> 👷(CI) trigger bundle-size-check only if necessary

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-export/mappingDocx.tsx
- src/frontend/apps/impress/src/features/docs/doc-export/mappingPDF.tsx
When exporting documents, if a inline code was inside a quote block, the PDF export was failing because the inline code was searching the GeistMono font in italics, which was not available.
We switch to the core "Courier" font for code marks, which is available in italics.
> 🐛(frontend) fix export when quote block and inline code

- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelFavorites.tsx
We recently change from a `div` to a `ul` for better semantics. `ul` include by default padding, we remove it to
align with the design.
> 🐛(frontend) remove padding from ul in left panel favorites

- CHANGELOG.md
- src/frontend/apps/impress/src/components/Box.tsx
- src/frontend/apps/impress/src/features/home/components/HomeSection.tsx
A section in the homepage was not displaying correctly anymore. This commit fixes the issue.
> 🐛(frontend) fix display bug on homepage

- .github/workflows/docker-hub.yml
Replace custom Docker Hub authentication with standard, secure, official GitHub actions for improved security and maintainability.
Uses officially supported actions that follow security best practices and receive regular updates from GitHub.
Avoid unsecure handling of GitHub secrets.
Thanks to @lebaudantoine
> 🔒️(all) refactor Docker Hub login to use official GitHub actions

- CHANGELOG.md
- src/frontend/apps/impress/src/components/DropButton.tsx
- src/frontend/apps/impress/src/components/dropdown-menu/DropdownMenu.tsx
- src/frontend/apps/impress/src/features/auth/components/ButtonLogin.tsx
- src/frontend/apps/impress/src/features/header/components/Header.tsx
- src/frontend/apps/impress/src/features/language/components/LanguagePicker.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LefPanelTargetFilters.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelFavoriteItem.tsx
standardizes keyboard focus appearance to improve UI coherence
This pull request unifies the focus style only in the header and the left panel.
It replaces default outlines with box-shadow and border-radius to deliver a
smoother, less abrupt experience for keyboard users.
⚠️ The main documentation page are excluded,
as they will be part of a broader accessibility rework in a future PR.
> ✨(frontend) unify tab focus style for better visual consistency

- src/frontend/apps/impress/src/features/docs/doc-editor/components/BlockNoteToolBar/ModalConfirmDownloadUnsafe.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModal.tsx
Recent improvement changes the modal title with a h1 tag, h1 tag adds margin by default.
We remove the margin from the h1 tag to stick to the design system.
> 💄(frontend) remove margin from modal title

- CHANGELOG.md
- src/backend/core/api/viewsets.py
- src/backend/core/tests/documents/test_api_documents_duplicate.py
Reader user should be able to duplicate a doc in the doc tree. It should be created a new doc at the root level.
Fixes https://github.com/suitenumerique/docs/issues/1329
> 🐛(backend) duplicate sub docs as root for reader user

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-tree.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-management/components/SimpleDocItem.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocSubPageItem.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocTree.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/hooks/useKeyboardActivation.ts
Enable keyboard accessibility for opening documents and subdocuments via the Enter key. This improves usability and accessibility for users navigating with the keyboard.
> ✨(frontend) enable enter key to open documents and subdocuments

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocsGridItem.tsx
Make documents visible in the list and allow users to open them using the Enter key.
Improves accessibility and user interaction with listed documents.
Clarify interaction:
https://github.com/user-attachments/assets/a0060794-4583-44b2-9dd7-f35d54b5771c
> ✨(frontend) add document visible in list and openable via enter key

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-export/blocks-mapping/headingPDF.tsx
- src/frontend/apps/impress/src/features/docs/doc-export/components/ModalExport.tsx
**Purpose**
This pull request introduces PDF bookmarks (outline) support in exported documents.
The goal is to provide an accessible outline structure based on document headings, in line with WCAG/RGAA requirements for navigable documents.
issue [1335](https://github.com/suitenumerique/docs/issues/1135)
**Proposal**
Investigations performed
- Tried attaching unique id values to headings.
- Tested with invisible anchors positioned before headings.
- Experimented with top, left, and fit options on bookmarks.
- Tried assigning explicit destination values (dest).
👉 In all cases, the behavior remains the same: all bookmarks on a given page point to the same destination (the last heading).
In my opinion the issue seems to be a limitation/bug in @react-pdf/renderer v4: bookmarks are generated in …
> ✨(frontend) add pdf outline property to enable bookmarks display

- CHANGELOG.md
- docker/auth/realm.json
- src/frontend/apps/e2e/__tests__/app-impress/doc-create.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-grid.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-inherited-share.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-member-create.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-member-list.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-tree.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-visibility.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/utils-share.ts
- src/frontend/apps/impress/src/features/docs/doc-header/components/DocHeader.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/__tests__/utils.test.tsx
- src/frontend/apps/impress/src/features/docs/doc-management/utils.ts
When we invited a user, this user on a child doc had his role indicating "owner" even if he was a "administrator".
Before the subpages feature, the user role was computed thanks to the abilities.
This is not the correct way to do it anymore, the abilities are now different.
We now have `user_role` in the doc response which is the correct way to get the user role for the current document.
> 🐛(frontend) fix legacy role computation

- CHANGELOG.md
- src/frontend/apps/impress/src/features/footer/Footer.tsx
- src/frontend/apps/impress/src/features/header/components/Header.tsx
- src/frontend/apps/impress/src/features/home/components/HomeContent.tsx
- src/frontend/apps/impress/src/layouts/MainLayout.tsx
- src/frontend/apps/impress/src/layouts/PageLayout.tsx
Improve accessibility by explicitly defining landmark roles in the HTML structure.
This helps users of assistive technologies navigate more efficiently and enhances
support across a wide range of browsers and screen readers.
issue : [878](https://github.com/suitenumerique/docs/issues/878)
Although HTML5 elements are recognized by modern tools, adding explicit role attributes ensures better support for older browsers and screen readers. This follows W3C recommendations and improves consistency across environments.
> ✨(frontend) improve accessibility by adding landmark roles to layout

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-export.spec.ts
- src/frontend/apps/impress/src/features/docs/doc-export/components/ModalExport.tsx
**Purpose**
Add document title to PDF and DOCX export metadata for better accessibility.
issue [1130](https://github.com/suitenumerique/docs/issues/1130)
**Proposal**
> ✨(docs) add title metadata to exported docx/pdf for accessibility

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/utils-sub-pages.ts
- src/frontend/apps/impress/src/components/Icon.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocTreeItemActions.tsx
Improve accessibility by hiding decorative icons from assistive technologies using aria-hidden. This prevents screen readers from announcing icons that are purely visual
This solves issue : [1390](https://github.com/suitenumerique/docs/issues/1390)
> ✨(frontend) hide decorative icons from assistive tech with aria-hidden

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-table-content.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/utils-editor.ts
- src/frontend/apps/e2e/__tests__/app-impress/utils-sub-pages.ts
- src/frontend/apps/impress/src/pages/docs/[id]/index.tsx
When navigating to a new document, the scroll position was preserved. 
This PR changes this behavior to scroll back to the top of the page when navigating to a new document.
Fixe: #1393
> 🐛(frontend) scroll back to top when navigate to a document

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/doc-member-create.spec.ts
- src/frontend/apps/e2e/__tests__/app-impress/utils-share.ts
- src/frontend/apps/e2e/__tests__/app-impress/utils-sub-pages.ts
- src/frontend/apps/impress/src/components/quick-search/QuickSearch.tsx
- src/frontend/apps/impress/src/components/quick-search/QuickSearchInput.tsx
- src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModal.tsx
- src/frontend/apps/impress/src/features/docs/doc-tree/components/DocTreeItemActions.tsx
Fix UX and accessibility violations in DocShareModal where QuickSearch auto-selected the first result on open, causing NVDA to immediately announce "John Doe impress@impress.world" despite focus being in the search input. 
This violated  UX principles (user consent, predictability) and WCAG
> ✨(frontend) improve NVDA navigation in DocShareModal

- CHANGELOG.md
- src/frontend/apps/impress/src/features/left-panel/components/LefPanelTargetFilters.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanel.tsx
- src/frontend/apps/impress/src/features/left-panel/components/LeftPanelFavorites.tsx
This PR improves the semantic structure and accessibility of the left panel ( TargetFilters and Favorites too) .
issue : [1429](https://github.com/suitenumerique/docs/issues/1429)
> ♿(frontend) improve semantic structure and aria roles of leftpanel

- src/frontend/apps/e2e/__tests__/app-impress/doc-grid-dnd.spec.ts
- src/frontend/apps/impress/src/features/docs/docs-grid/components/DocGridContentList.tsx
To move a doc you have to be at least admin of the destination doc.
It was written editor in the alert banner.
Change editor for administrator
> 💬(copy) wrong permission mentionned on move doc

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-editor/components/custom-blocks/CalloutBlock.tsx
Ensure proper permissions handling in callouts by preventing users with reader role from editing the emoji.
https://github.com/user-attachments/assets/37f71fb8-ef3d-4cc7-b356-3c649aa9a0d3
issue : [1410](https://github.com/suitenumerique/docs/issues/1410)
> 🔒(frontend) prevent readers from changing callout emoji

- CHANGELOG.md
- src/frontend/apps/impress/src/features/docs/doc-management/components/DocPage403.tsx
- src/frontend/apps/impress/src/pages/401.tsx
- src/frontend/apps/impress/src/pages/404.tsx
Align the "no access" image size with design mockups and improve its rendering on high pixel density (HiDPI) screens. This enhances visual consistency and clarity across devices.
[709](https://github.com/suitenumerique/docs/issues/709)
> 🐛(frontend) reduce no access image size from 450 to 300

- Dockerfile
- docs/examples/helm/impress.values.yaml
- src/helm/env.d/dev/values.impress.yaml.gotmpl
The certifi ca certificate is now stored under a static path (/cert/cacert.pem) to avoid issues when python is upgraded and the path to the certificate changes.
- Move the certifi cacert to a static path and create a symlink to this path
> 🚚(docker) use static path for certifi ca certificate
